include::../shared-doc/attributes.adoc[]

= wicket-war: Wicket Framework used in a WAR.
:author: Ondrej Zizka <ozizka@redhat.com>
:level: Intermediate
:technologies: Apache Wicket, JPA

[abstract]
Demonstrates how to use the Wicket Framework 7.x with the JBoss server using the Wicket Jakarta EE integration packaged as a WAR

:standalone-server-type: default
:archiveType: war

== What is it?

This is an example of how to use Wicket Framework 7.x with WildFly, leveraging features of {javaVersion}, using the Wicket-Stuff Jakarta EE integration.

Features used:

* Injection of `@PersistenceContext`
* Injection of a value from `web.xml` using `@Resource`
* Injection of a stateless session bean using `@EJB`

This is a WAR version.

// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
//  Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]
//  Start the {productName} Standalone Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]
//  Build and Deploy the Quickstart
include::../shared-doc/build-and-deploy-the-quickstart.adoc[leveloffset=+1]

== Access the application

Access the running application in a browser at the following URL: http://localhost:8080/{artifactId}/

You will see a page with a table listing user entities. Initially, this table is empty. By clicking a link, you can add more users.

// Undeploy the Quickstart
include::../shared-doc/undeploy-the-quickstart.adoc[leveloffset=+1]

== Debug the Application

If you want to debug the source code or look at the Javadocs of any library in the project,
run either of the following commands to pull them into your local repository. The IDE should then detect them.

[source,options="nowrap"]
----
$ mvn dependency:sources
$ mvn dependency:resolve -Dclassifier=javadoc
----
