= QUICKSTART_NAME: Brief Description of the Quickstart (try to limit the description to 55 characters)
:author: YOUR_NAME and optional CONTACT_INFO
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: [one of the following: Beginner, Intermediate, or Advanced]
:technologies: (list technologies used here)
:source: (The URL for the repository that is the source of record for this quickstart)
:prerequisites: (list any quickstarts that must be deployed prior to running this one)

[abstract]
(A brief description of the quickstart to appear in the table and in Google search SEO results. Try to limit the description to 155 characters )

_NOTE: This file is meant to serve as a template or guideline for your own quickstart README.md file:_

* _The first lines in the file after the quickstart name and description (Author:, Level:, etc.) are metadata tags used by the http://www.jboss.org/developer-materials/#!formats=jbossdeveloper_quickstart[JBoss Developer site]. Make sure you include 2 spaces at the end of each line so they also render correctly when rendered as HTML files._
* _Be sure to replace the `QUICKSTART_NAME` and `YOUR_NAME` variables in your `README` file with the appropriate values._
* _Contributor instructions are enclosed within comments `&lt;!-- Contributor: --&gt;`. These instructions are only meant to help you and you should NOT include them in your README file!_
* _Review the other quickstart `README` files if you need help with formatting or content._

== What is it?

The `QUICKSTART_NAME` quickstart demonstrates … in {productNameFull}.
 * What are the technologies demonstrated by the quickstart?
 * What does it do when you run it?

You should include any information that would help the user understand the quickstart.

If possible, give an overview, including any code they should look at to understand how it works..

== System Requirements

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

All you need to build this project is {buildRequirements}. See https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONFIGURE_MAVEN_JBOSS_EAP7.md#configure-maven-to-build-and-deploy-the-quickstarts[Configure Maven for {productName} {productVersion}] to make sure you are configured correctly for testing the quickstarts.

== Use of {jbossHomeName}

In the following instructions, replace `{jbossHomeName}` with the actual path to your {productName} installation. The installation path is described in detail here: https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/USE_OF_{jbossHomeName}.md#use-of-eap_home-and-jboss_home-variables[Use of {jbossHomeName} and JBOSS_HOME Variables].

== Configure Optional Components

* This quickstart uses a secured management interface and requires that you create a management (or application) user to access the running application. Instructions to set up a Management (or Application) user can be found here:

** https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CREATE_USERS.md#add-a-management-user[Add a Management User]

** https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CREATE_USERS.md#add-an-application-user[Add an Application User]

* This quickstart requires the PostgreSQL database. Instructions to install an configure PostgreSQL can be found here: https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONFIGURE_POSTGRESQL_EAP7.md#configure-the-postgresql-database-for-use-with-the-quickstarts[Configure the PostgreSQL Database for Use with the Quickstarts]

* This quickstart uses Byteman to help demonstrate crash recovery. Instructions to install and configure Byteman can be found here: https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONFIGURE_BYTEMAN.md#configure-byteman-for-use-with-the-quickstarts[Configure Byteman for Use with the Quickstarts]

== Start the Server

* Start the {productName} Server

* Start the {productName} Server with the Full Profile

* Start the {productName} Server with Custom Options. You will need to provide the argument string to pass on the command line, for example:

`--server-config=../../docs/examples/configs/standalone-xts.xml`

== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a command prompt and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:

----
mvn clean install wildfly:deploy
----

. This will deploy `target/{artifactId}.war` (or `target/{artifactId}.ear`) to the running instance of the server.

== Access the Application

----
    Access the running application in a browser at the following URL:  <http://localhost:8080/{artifactId}>
----

----
    You will be presented with a simple form for adding key/value pairs and a checkbox to indicate whether the updates should be executed using an unmanaged component.

        If the box is checked, the updates will be executed within a session bean method.
        If the box is not checked, the transactions and JPA updates will run in a servlet instead of session beans.

    To list all existing key/value pairs, leave the key input box empty.

    To add or update the value of a key, enter a key and value input boxe and click the submit button to see the results.
----

== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a command prompt and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:

----
mvn wildfly:undeploy
----

== Run the Arquillian Tests (For quickstarts that contain Arquillian tests)

This quickstart provides Arquillian tests. By default, these tests are configured to be skipped as Arquillian tests require the use of a container.

. Make sure you have started the {productName} server as described above.
. Open a command prompt and navigate to the root directory of this quickstart.
. Type the following command to run the test goal with the following profile activated:

----
mvn clean verify -Parq-remote
----

You can also let Arquillian manage the {productName} server by using the `arq-managed` profile. For more information about how to run the Arquillian tests, see https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/RUN_ARQUILLIAN_TESTS.md#run-the-arquillian-tests[Run the Arquillian Tests].

== Investigate the Console Output

* If applicable, copy and paste output from the JUnit tests to show what to expect in the console from the tests.

== Investigate the Server Log

* If applicable, copy and paste log messages output by the application to show what to expect in the server log when running the tests.

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

----
mvn dependency:sources
----