= __QUICKSTART_NAME__: Brief Description of the Quickstart (try to limit the description to 55 characters)
:author: __YOUR_NAME__ and optional CONTACT_INFO
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../shared-doc/attributes.adoc[]
////
:uses-h2: Define this variable if the quickstart uses the H2 database.
:uses-ds-xml: Define this variable if the quickstart uses an *-ds.xml file.
:performance-scalability: Define this variable if you need to consider scalability.
:uses-cli: Define this variable if CLI configuration scripts are provided.
////

:level: [one of the following: Beginner, Intermediate, or Advanced]
:technologies: (list technologies used here)
:source: (The URL for the repository that is the source of record for this quickstart)
:prerequisites: (list any quickstarts that must be deployed prior to running this one)

[abstract]
(Create a  brief description of the quickstart. This description appears in the table and in Google search SEO results. Try to limit the description to 155 characters )

[IMPORTANT]
====
This file is meant to serve as a template or guideline for your own quickstart `README.adoc` file:

* The first lines in the file after the quickstart name and description (Author:, Level:, etc.) are metadata tags used by the http://www.jboss.org/developer-materials/#!formats=jbossdeveloper_quickstart[JBoss Developer site]. Make sure you include 2 spaces at the end of each of these lines so they also render correctly when rendered as HTML files.
* Make sure you replace the `__QUICKSTART_NAME__` and `__YOUR_NAME__` variables in your `README.adoc` file with the appropriate values.
* These instructions are only meant to help you and you should NOT include them in your README file!
* Review the other quickstart `README.adoc` files if you need help with formatting or content.
====

[[what_is_it]]
== What is it?

Start the text with "The `__QUICKSTART_NAME__` quickstart demonstrates … in {productNameFull}."

 * You should list the technologies demonstrated by the quickstart.
 * You should explain how it works and what to expect when you run it?

You should include any information that would help the user understand the quickstart.

If possible, give an overview, including any code they should look at to understand how it works..

////
    Include this "Considerations for Use in a Production Environment" file
    in the following is true for your quickstart:
    * It uses the H2 database. Be sure to define the `:uses-h2:` variable.
    * It uses a `*-ds.xml` file. Be sure to define the `:uses-ds-xml:` variable.
    * It has performance and scalability considerations. Define the `:performance-scalability:` variable.
////
//***************************************
// Add notes about use in a production environment.
//***************************************
include::../shared-doc/development-shortcuts.adoc[leveloffset=+1]

////
    Always add the system requirements.
    If this quickstart uses CLI scripts, be sure to define the :uses-cli: variable.
    Add any additional requirements for this quickstart after the include.
////
//*************************************************
// Add System Requirements
//*************************************************
include::../shared-doc/system-requirements.adoc[leveloffset=+1]

////
    Add the following if you refer to the {jbossHomeName}.
////
//*************************************************
// Add Use of JBoss Home Name
//*************************************************
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]

[[configure_optional_components]]
== Configure Optional Components

* If the quickstart uses a secured management interface and requires that you create a management or application user to access the running application, provide instructions to set up a management or application user. Optionally point them to additional information, for example:

** link:{addManagementUserDocUrl}[Add a Management User]

** link:{addApplicationUserDocUrl}[Add an Application User]

* If the quickstart requires the PostgreSQL database, provide instructions to install and configure PostgreSQL. Provide a link to the instructions here here: link:{configurePostgresDocUrl}[Configure the PostgreSQL Database for Use with the Quickstarts]

* If the quickstart uses Byteman to help demonstrate crash recovery, let them know that instructions to install and configure Byteman can be found here: link:{configureBytemanQuickstartsDocUrl}[Configure Byteman for Use with the Quickstarts]

[[start_the_server]]
== Start the Server

* To start the {productName} server with the default profile, copy the following content into the README file:
+
[source,subs="+quotes",subs="attributes+",options="nowrap"]
----
//*************************************************
// Start the server with the default profile
//*************************************************
// == Start the Server with the Default Profile
 include::../shared-doc/start-server-default-profile.adoc[leveloffset=+1]
----

* To start the {productName} server with the full profile, copy the following content into the README file:
+
[source,subs="+quotes",subs="attributes+",options="nowrap"]
----
//*************************************************
// Start the server with the full profile
//*************************************************
// == Start the Server with the Full Profile
 include::../shared-doc/start-server-full-profile.adoc[leveloffset=+1]
----

* To start the {productName} server with custom options

** You must provide instructions similar to the ones copied in above.
** You need to provide the argument string to pass on the command line, for example:
+
[source,subs="+quotes",options="nowrap"]
----
--server-config=../../docs/examples/configs/standalone-xts.xml
----

[[build_and_deploy_the_quickstart]]
== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:
+
[source,options="nowrap"]
----
$ mvn clean install wildfly:deploy
----

. This will deploy `target/{artifactId}.war` (or `target/{artifactId}.ear`) to the running instance of the server.

[[access_the_application]]
== Access the Application

Access the running application in a browser at the following URL:  http://localhost:8080/{artifactId}

Describe what the user should look for in the running application.


== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:
+
[source,options="nowrap"]
----
$ mvn wildfly:undeploy
----

== Run the Arquillian Tests

If the quickstart provides Arquillian tests, let them know.

This quickstart provides Arquillian tests. By default, these tests are configured to be skipped as Arquillian tests require the use of a container.

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type the following command to run the test goal with the following profile activated:
+
[source,options="nowrap"]
----
$ mvn clean verify -Parq-remote
----

You can also let Arquillian manage the {productName} server by using the `arq-managed` profile. For more information about how to run the Arquillian tests, see link:{arquillianTestsDocUrl}[Run the Arquillian Tests].

== Investigate the Console Output

* If applicable, copy and paste output from the JUnit tests to show what to expect in the console from the tests.

== Investigate the Server Log

* If applicable, copy and paste log messages output by the application to show what to expect in the server log when running the tests.

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

[source,options="nowrap"]
----
$ mvn dependency:sources
----
