include::../shared-doc/attributes.adoc[]

= deltaspike-beanbuilder: Shows how to create new beans using DeltaSpike utilities
:author: Rafael Benevides
:level: Advanced
:technologies: CDI, DeltaSpike

[abstract]
Shows how to create new beans using DeltaSpike utilities.

== What is it?

This project demonstrates a CDI Portable Extension that uses DeltaSpike utilities to create new Beans.

This extension permits the injection of JPA entities by id, without the need to query it. To achieve this, the extension observes the `ProcessInjectionTarget` event and get locates all the injection points that have requested injection by id. In `AfterBeanDiscovery` event, the extension creates `Bean` instances using the `BeanBuilder` utility.

The project contains a very simple JPA entity class, the extension class, the service registration file for that extension and an Arquillian test to verify the extension is working correctly.

It does not contain any user interface; the tests must be run to verify everything is working correctly.

// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
// Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]
// Start the Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]
//  Run the Arquillian Tests
include::../shared-doc/run-arquillian-tests.adoc[leveloffset=+1]


== Run the Tests in {JBDSProductName} or Eclipse

To run the tests in {JBDSProductName}, first set the active Maven profile in the project properties to be either `arq-jbossas-managed`, for running on a managed server, or `arq-jbossas-remote`, for running on remote server.

To run the tests, right click on the project or individual classes and select *Run As* –&gt; *JUnit Test* in the context menu.

== Investigate the Console Output

Maven prints a summary of the performed tests in the console:

[source,options="nowrap"]
----
——————————————————-
 T E S T S
 ——————————————————-
 Running org.jboss.as.quickstart.deltaspike.beanbuilder.test.ByIdExtensionTest
 log4j:WARN No appenders could be found for logger (org.jboss.logging).
 log4j:WARN Please initialize the log4j system properly.
 Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.641 sec

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

// Run the Quickstart in Red Hat CodeReady Studio or Eclipse
include::../shared-doc/run-the-quickstart-in-jboss-developer-studio.adoc[leveloffset=+1]

== Debug the Application

If you want to debug the source code or look at the Javadocs of any library in the project, run either of the following commands to pull them into your local repository. The IDE should then detect them.

[source,options="nowrap"]
----
$ mvn dependency:sources
$ mvn dependency:resolve -Dclassifier=javadoc
----
