= ejb-remote: Remote EJB Client Example
:author: Jaikiran Pai, Mike Musgrove
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: Intermediate
:technologies: EJB, JNDI
:source: {githubRepoUrl}

[abstract]
The `ejb-remote` quickstart uses *EJB* and *JNDI* to demonstrate how to access an EJB, deployed to {productName}, from a remote Java client application.

== What is it?

The `ejb-remote` quickstart shows how to access an EJB from a remote Java client application. It demonstrates the use of _EJB_ and _JNDI_ in {productNameFull}.

There are two components to this example:

. A server side component:
+
The server component is comprised of a stateful EJB and a stateless EJB. It provides both an EJB JAR that is deployed to the server and a JAR file containing the remote business interfaces required by the remote client application.

. A remote client application that accesses the server component.
+
The remote client application depends on the remote business interfaces from the server component. This application looks up the stateless and stateful beans via JNDI and invokes a number of methods on them.

Each component is defined in its own standalone Maven module. The quickstart provides a top level Maven module to simplify the packaging of the artifacts.

== System Requirements

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

All you need to build this project is {buildRequirements}. See link:{configureMavenDocUrl}[Configure Maven to Build and Deploy the Quickstarts] to make sure you are configured correctly for testing the quickstarts.

== Use of {jbossHomeName}

In the following instructions, replace `__{jbossHomeName}__` with the actual path to your {productName} installation. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of {jbossHomeName} and JBOSS_HOME Variables].

== Start the Server

. Open a terminal and navigate to the root of the {productName} directory.
. The following shows the command line to start the server:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

== Build and Deploy the Quickstart

Since this quickstart builds two separate components, you can not use the standard _Build and Deploy_ commands used by most of the other quickstarts. You must follow these steps to build, deploy, and run this quickstart.

. Make sure you have started the {productName} server. See the instructions in the previous section.
. Open a terminal and navigate to the ejb-remote quickstart directory
. Build and install the server side component:
** Build the EJB and client interfaces JARs and install them in your local Maven repository.
+
----
$ mvn clean install
----

** Deploy the EJB JAR to your server. This Maven goal will deploy `server-side/target/{artifactId}-server-side.jar`. You can check the {productName} server console to see information messages regarding the deployment.
+
----
$ mvn wildfly:deploy
----

. Build and run the client application
** Navigate to the client subdirectory:
+
----
$ cd ../client
----

** Compile the client code
+
----
$ mvn clean compile
----

** Execute the client application within Maven
+
----
$ mvn exec:exec
----

== Investigate the Console Output

When the client application runs, it performs the following steps:

. Obtains a stateless session bean instance.
. Sends method invocations to the stateless bean to add two numbers, and then displays the result.
. Sends a second invocation to the stateless bean subtract two numbers, and then displays the result.
. Obtains a stateful session bean instance.
. Sends several method invocations to the stateful bean to increment a field in the bean, displaying the result each time.
. Sends several method invocations to the stateful bean to decrement a field in the bean, displaying the result each time.

The output in the terminal window will look like the following:

----
  Obtained a remote stateless calculator for invocation
  Adding 204 and 340 via the remote stateless calculator deployed on the server
  Remote calculator returned sum = 544
  Subtracting 2332 from 3434 via the remote stateless calculator deployed on the server
  Remote calculator returned difference = 1102
  Obtained a remote stateful counter for invocation
  Counter will now be incremented 5 times
  Incrementing counter
  Count after increment is 1
  Incrementing counter
  Count after increment is 2
  Incrementing counter
  Count after increment is 3
  Incrementing counter
  Count after increment is 4
  Incrementing counter
  Count after increment is 5
  Counter will now be decremented 5 times
  Decrementing counter
  Count after decrement is 4
  Decrementing counter
  Count after decrement is 3
  Decrementing counter
  Count after decrement is 2
  Decrementing counter
  Count after decrement is 1
  Decrementing counter
  Count after decrement is 0
----

Logging statements have been removed from this output here to make it clearer.

== Build and Run The Quickstart as an Executable JAR

The remote client application can also be built as a standalone executable JAR with all of its dependencies.

. Open a terminal and navigate to the ejb-remote/client quickstart directory
+
----
$ cd client
----

. Type the following in the command line:
+
----
$ mvn clean package assembly:single
----

. You can then run the executable JAR using the `java -jar` command. You will see the same console output as above.
+
----
$ java -jar target/{artifactId}-client-jar-with-dependencies.jar
----

== Undeploy the Archive

To undeploy the server-side component from the {productName} server:

. Navigate to the server-side subdirectory:
+
----
$ cd ../server-side
----

. Type the following command:
+
----
$ mvn wildfly:undeploy
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

This quickstart consists of multiple projects, so it deploys and runs differently in JBoss Developer Studio than the other quickstarts.

. Install the required Maven artifacts and deploy the server side of the quickstart project.

** Right-click on the *{artifactId}-server-side* project and choose *Run As* -> *Maven Install*.
** Right-click on the *{artifactId}-server-side* project and choose *Run As* -> *Run on Server*.
. Build and run the client side of the quickstart project.

** Right-click on the *{artifactId}-client* project and choose *Run As* -> *Java Application*.
** In the *Select Java Application* window, choose *RemoteEJBClient - org.jboss.as.quickstarts.ejb.remote.client* and click *OK*.
** The client output displays in the *Console* window.
. To undeploy the project, right-click on the *{artifactId}-server-side* project and choose *Run As* -> *Maven build*. Enter `wildfly:undeploy` for the *Goals* and click *Run*.

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

----
$ mvn dependency:sources
----
