include::../shared-doc/attributes.adoc[]

= app-client: Use the {productName} Application Client Container

:author: Wolf-Dieter Fink
:level: Intermediate
:technologies: EJB, EAR, AppClient

[abstract]
The `app-client` quickstart demonstrates how to code and package a client app and use the {productName} client container to start the client `Main` program.

:standalone-server-type: default
:archiveType: ear

== What is it?

The `app-client` quickstart demonstrates how to use the {productName} client container to start the client `Main` program and provide Dependency Injections (DI) for client applications in {productNameFull}. It also shows you how to use Maven to package the application according to the Jakarta EE specification.

This example consists of the following Maven projects, each with a shared parent.

[cols="30%,70%",options="headers"]
|===
|Project |Description

| `ejb`
| This project contains the EJB code that can be called by the client.

| `client-simple`
| This project contains a simple client application that runs in the application-client container to show the injection.

| `ear`
| This project builds the EAR artifact and pulls in the EJB and client artifacts.

|===

The root `pom.xml` file builds each of the subprojects in the appropriate order.

// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
// Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]
// Add the Authorized Application and Management Users
include::../shared-doc/add-application-and-management-users.adoc[leveloffset=+1]
// Start the Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]
// Build and Deploy the Quickstart
include::../shared-doc/build-and-deploy-the-quickstart.adoc[leveloffset=+1]

== Access the Remote Client Application from the Same Machine

This example shows how to invoke an EJB from a remote standalone application on the same machine. Both the client and server are on the same machine, so the defaults are sufficient and no authentication is necessary.

. Verify that the quickstart deployed successfully as described above.
. Navigate to the root directory of this quickstart and type the following command to run the application. Make sure you replace `__{jbossHomeName}__` with the path to your {productName} installation.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/appclient.sh ear/target/app-client.ear#simpleClient.jar Hello from command line
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\appclient.bat` script.

. Review the result. The client outputs the following information, which is provided by the server application.
+
[source,options="nowrap"]
----
[org.jboss.as.quickstarts.appclient.acc.client.Main] (Thread-51) Main started with arguments
[org.jboss.as.quickstarts.appclient.acc.client.Main] (Thread-51) [Hello, from, command, line]
[org.jboss.as.quickstarts.appclient.acc.client.Main] (Thread-##) Hello from StatelessSessionBean@myhost
----
+
The client output shows that the `ServerApplication` is called at the jboss.node `myhost`. The application client connected automatically a server on the same machine.

. Review the server log files to see the bean invocations on the server.
+
[source,options="nowrap"]
----
ClientContext is here = {Client =dev84, jboss.source-address=localhost/127.0.0.1:45315}
----

== Access the Remote Client Application from a Different Machine

This example shows how to invoke an EJB from a remote standalone Jakarta EE application on a different machine. In this case, the client needs to define a properties file to define properties to connect and authenticate to the server. The properties file is passed on the command line using the `--ejb-client-properties` argument.

=== Configure Machine_1 (Remote Server Machine)

. Install {productName} on this machine.
. xref:add_the_application_management_users[Add the authorized application and management users] to the {productName} server on this machine as described above.
. Start the {productName} server with the following command, replacing `__MACHINE_1_IP_ADDRESS__` with the IP address of this machine. These arguments make the server accessible to the network.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh -b __MACHINE_1_IP_ADDRESS__ -bmanagement __MACHINE_1_IP_ADDRESS__
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.


=== Configure Machine_2 (Local Client Machine)

. Install {productName} on this server. There is no need to add the application users to this server.
. Download the `app-client` quickstart to this machine.
. Create a `jboss-ejb-client.properties` file. This file can be located anywhere in the file system, but for ease of demonstration, we create it in the root directory of this quickstart. Add the following content, replacing `__MACHINE_1_IP_ADDRESS__` with the IP address of `Machine_1`.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
remote.connectionprovider.create.options.org.xnio.Options.SSL_ENABLED=false
remote.connections=default
remote.connection.default.host=__MACHINE_1_IP_ADDRESS__
remote.connection.default.port=8080
remote.connection.default.connect.options.org.xnio.Options.SASL_POLICY_NOANONYMOUS=false
remote.connection.default.username=quickstartUser
remote.connection.default.password=quickstartPwd1!
----

. Open a terminal and navigate to the root directory of the quickstart.

. Deploy the `app-client` quickstart to the remote machine using the following command. Make sure you replace `__MACHINE_1_IP_ADDRESS__` with the IP address of `Machine_1`.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ mvn clean install wildfly:deploy -Dwildfly.hostname=__MACHINE_1_IP_ADDRESS__ [-Dwildfly.port=9099] -Dwildfly.username=quickstartAdmin -Dwildfly.password=adminPwd1!
----

. Verify that the quickstart deployed successfully and the server is running on `Machine_1` as described above.
. Type the following command to run the `app-client` application.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/appclient.sh --ejb-client-properties=ejb-client.properties ear/target/app-client.ear#simpleClient.jar Hello from command
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\appclient.bat` script.

. Review the result. The client outputs the following information, which was provided by the application.
+
[source,options="nowrap"]
----
[org.jboss.as.quickstarts.appclient.acc.client.Main] (Thread-51) Main started with arguments
[org.jboss.as.quickstarts.appclient.acc.client.Main] (Thread-51)             [Hello, from, command, line]
[org.jboss.as.quickstarts.appclient.acc.client.Main] (Thread-##) Hello from StatelessSessionBean@theOtherHOST
----
+
The client output shows that the `ServerApplication` is called at the jboss.node `theOtherHOST`.

. Review the server log files on the remote machine to see the bean invocations on the server.
+
[source,options="nowrap"]
----
ClientContext is here = {Client =dev84, jboss.source-address=localhost/127.0.0.1:45315}
----
+
As shown above, the connected servers can be configured using the properties file. It is also possible to connect multiple servers or a cluster using the same `jboss-ejb-client.properties` file.

== Undeploy the Archive from the Local Machine

Follow these instructions if you are testing the quickstart on the same machine.

. Make sure you have started the {productName} server on the machine where the quickstart is deployed as described above.
. Open a terminal on that server and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive from the local machine.
+
[source,options="nowrap"]
----
$ mvn wildfly:undeploy
----

== Undeploy the Archive from the Remote Machine

Follow these instructions if you are testing the quickstart on a different machine.

. Make sure you have started the {productName} server on the remote server machine, `Machine_1`, where the quickstart is deployed as described above.
. Open a terminal on the local client machine, `Machine_2`, and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive from the remote server machine, `Machine_1`.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ mvn wildfly:undeploy -Dwildfly.hostname=__MACHINE_1_IP_ADDRESS__ [-Dwildfly.port=9099] -Dwildfly.username=quickstartAdmin -Dwildfly.password=adminPwd1!
----
