= websocket-hello: A simple WebSocket application
:author: Sande Gilda, Emmanuel Hugonett
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: Beginner
:technologies: WebSocket, CDI, JSF
:source: {githubRepoUrl}

[abstract]
The `websocket-hello` quickstart demonstrates how to create a simple WebSocket application.

== What is it?

The `websocket-hello` quickstart demonstrates how to create a simple WebSocket-enabled application in {productNameFull}. It consists of the following:

* A JavaScript enabled WebSocket HTML client.
* A WebSocket server endpoint that uses annotations to interact with the WebSocket events.
* A `jboss-web.xml` file configured to enable WebSockets

WebSockets are a requirement of the Java EE 7 specification and are implemented in {productName} {productVersion}. They are configured in the `undertow` subsystem of the server configuration file. This quickstart uses the WebSocket default settings, so it is not necessary to modify the server configuration to deploy and run this quickstart.

_Note: This quickstart demonstrates only a few of the basic functions. A fully functional application should provide better error handling and intercept and handle additional events._

== System Requirements

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

All you need to build this project is {buildRequirements}. See https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONFIGURE_MAVEN_JBOSS_EAP7.md#configure-maven-to-build-and-deploy-the-quickstarts[Configure Maven for {productName} {productVersion}] to make sure you are configured correctly for testing the quickstarts.

== Use of {jbossHomeName}

In the following instructions, replace `{jbossHomeName}` with the actual path to your {productName} installation. The installation path is described in detail here: https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/USE_OF_{jbossHomeName}.md#use-of-eap_home-and-jboss_home-variables[Use of {jbossHomeName} and JBOSS_HOME Variables].

== Start the {productName} Server

. Open a command prompt and navigate to the root of the {productName} directory.
. The following shows the command line to start the server:

[subs=normal]
----
For Linux:   {jbossHomeName}/bin/standalone.sh
For Windows: {jbossHomeName}\bin\standalone.bat
----

== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a command prompt and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:

----
mvn clean install wildfly:deploy
----

. This will deploy `target/{artifactId}.war` to the running instance of the server.

== Access the Application

The application will be running at the following URL: http://localhost:8080/{artifactId}/.

. Click on the `Open Connection` button to create the WebSocket connection and display current status of `Open`.
. Type a name and click `Say Hello` to create and send the `Say hello to &lt;NAME&gt;` message. The message appears in the server log and a response is sent to the client.
. Click on the `Close Connection` button to close the WebSocket connection and display the current status of `Closed`.
. If you attempt to send another message after closing the connection, the following message appears on the page:

----
WebSocket connection is not established. Please click the Open Connection button.
----

== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a command prompt and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:

----
mvn wildfly:undeploy
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

----
    mvn dependency:sources
----