include::shared-doc/attributes.adoc[]

= {productNameFull} ({productName}) Quickstarts

[abstract]
The quickstarts demonstrate {javaVersion} and a few additional technologies from the {productNameFull} stack. They provide small, specific, working examples that can be used as a reference for your own project.

// The Product builds provide the README.html files. so the following admonition is not needed there.
ifndef::ProductRelease[]
[IMPORTANT]
====
The quickstart `README` files are written in AsciiDoc, not only because the language is much more powerful than Markdown, but also also because it is possible to extract common instructions into separate files to be reused across the quickstarts. While this makes them more flexible and easier to maintain, unfortunately, included files do not render in a readable format in GitHub or in most text editors.

The Maven plugin that is used to build and deploy the quickstarts can also generate fully rendered `README.html` instructions from the `README.adoc` files. For instructions on how to generate these files, see https://github.com/wildfly/quickstart/blob/master/CONTRIBUTING.adoc#build_the_quickstart_readme_files[Build the README.html Files] in the _CONTRIBUTING_ guide.
====
// End ifndef::ProductRelease[]
endif::[]

//*****************************************************************************
// Begin Non-CD release Project (WildFly) and Product (JBoss EAP) instructions
//*****************************************************************************
ifndef::EAPCDRelease[]

[[introduction]]
== Introduction

// JBoss EAP
ifdef::ProductRelease[]
These quickstarts run on {productNameFull} {productVersion}. Each quickstart folder contains a `README{outfilesuffix}` file that describes the quickstart features and provides instructions about how to build and run it.

We recommend that you use the *{quickstartDownloadName}* ZIP file, which you can download from the {quickstartDownloadUrl}[{ProductShortName} Software Download] page on the Red Hat Customer Portal. This version of the quickstarts uses the correct dependencies and ensures that you test and compile against the correct server runtime environment.

// End ifdef::ProductRelease[]
endif::[]

// WildFly
ifndef::ProductRelease[]
These quickstarts run on {productNameFull}. Each quickstart folder contains a `README{outfilesuffix}` file that describes the quickstart features and provides instructions about how to build and run it.

The quickstarts are configured to use the correct Maven dependencies and ensure that you test and compile the quickstarts against the correct runtime environment.
// End ifndef::ProductRelease[]
endif::[]

Make sure you read this entire document before you attempt to work with the quickstarts. It contains the following information:

* xref:suggested_approach_to_the_quickstarts[Suggested Approach to the Quickstarts]: A suggested approach on how to work with the quickstarts.
* xref:system_requirements[System Requirements]: List of software required to run the quickstarts.
* link:{configureMavenDocUrl}[Configure Maven]: How to configure the Maven repository for use by the quickstarts.
* xref:run_the_quickstarts[Run the Quickstarts]: General instructions for building, deploying, and running the quickstarts.
* link:{arquillianTestsDocUrl}[Run the Arquillian Tests]: How to run the Arquillian tests provided by some of the quickstarts.
* xref:optional_components[Optional Components]: How to install and configure optional components required by some of the quickstarts.
* https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONTRIBUTING.adoc#jboss_developer_contributing_guide[Contributing Guide]: This document contains information targeted for developers who want to contribute to {productName} developer projects.
* xref:available_quickstarts[Available Quickstarts]: List of the available quickstarts and details about each one.

[[use_of_product_home_and_jboss_home_variables]]
== Use of {jbossHomeName} and JBOSS_HOME Variables

The quickstart `README` files use the _replaceable_ value `__{jbossHomeName}__` to denote the path to the {productName} installation. When you encounter this value in a `README` file, make sure you replace it with the actual path to your {productName} installation. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of __{jbossHomeName}__ and __JBOSS_HOME__ Variables].

// Suggested Approach to the Quickstarts
include::shared-doc/suggested-approach.adoc[leveloffset=+1]

[[system_requirements]]
== System Requirements

The applications these projects produce are designed to be run on {productNameFull} {productVersion} or later.

All you need to build these projects is {buildRequirements}. See link:{configureMavenDocUrl}[Configure Maven to Build and Deploy the Quickstarts] to make sure you are configured correctly for testing the quickstarts.

To run these quickstarts with the provided build scripts, you need the {productName} distribution ZIP. For information on how to install and run JBoss, see the {LinkGettingStartedGuide}[__{GettingStartedBookName}__] located on the Red Hat Customer Portal.

You can also run the quickstarts in xref:run_the_quickstarts_in_jboss_developer_studio_or_eclipse[{JBDSProductName} or Eclipse].

[[run_the_quickstarts]]
== Run the Quickstarts

[[build_and_deploy_a_quickstart]]
=== Build and Deploy a Quickstart

The root folder of each individual quickstart contains a `README{outfilesuffix}` file with detailed instructions on how to build and run the example. In most cases you do the following:

* Start the {productName} server.
* Build the archive.
* Deploy the quickstart.
* Undeploy the quickstart when you are finished testing.

[[verify_all_quickstarts_build_with_one_command]]
=== Verify All Quickstarts Build with One Command

You can also verify that all of the quickstarts build using one command. However, quickstarts that have complex dependencies must be skipped. For example, the `resteasy-jaxrs-client` quickstart is a RESTEasy client that depends on the deployment of the `helloworld-rs` quickstart. The root `pom.xml` file defines a `complex-dependencies` profile to exclude these quickstarts from the root build process.

To build all of the quickstarts:

. Open a terminal and navigate to the root directory of the quickstarts.
. Use the following command to build the quickstarts that do not have complex dependencies:
+
[source,options="nowrap"]
----
$ mvn clean install '-Pdefault,!complex-dependencies'
----

[[undeploy_all_deployed_quickstarts_with_one_command]]
=== Undeploy All Deployed Quickstarts with One Command

To undeploy all of the the quickstarts from the root of the quickstart folder, you must pass the argument `-fae` (fail at end) on the command line. This allows the command to continue past quickstarts that fail due to complex dependencies or only have Arquillian tests and do not deploy archives to the server.

You can undeploy quickstarts using the following procedure:

. Start the {productName} server.
. Open a terminal and navigate to the root directory of the quickstarts.
. Use the following command to undeploy any deployed quickstarts.
+
[source,options="nowrap"]
----
$ mvn wildfly:undeploy -fae
----

To undeploy any quickstarts that fail due to complex dependencies, follow the undeploy procedure described in the quickstart's `README{outfilesuffix}` file.

[[run_the_quickstarts_in_jboss_developer_studio_or_eclipse]]
== Run the Quickstarts in {JBDSProductName} or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use {JBDSProductName} or Eclipse to Run the Quickstarts].

[[optional_components]]
== Optional Components

The following components are needed for only a small subset of the quickstarts. Do not install or configure them unless the quickstart requires it.

* link:{addUserDocUrl}[Create Users Required by the Quickstarts]: Add a Management or Application user for the quickstarts that run in a secured mode.

* link:{configurePostgresDocUrl}[Configure the PostgreSQL Database for Use with the Quickstarts]: The PostgreSQL database is used for the distributed transaction quickstarts.

* link:{configureBytemanQuickstartsDocUrl}[Configure Byteman for Use with the Quickstarts]: This tool is used to demonstrate crash recovery for distributed transaction quickstarts.

// Available Quickstarts
include::shared-doc/available-quickstarts.adoc[leveloffset=+1]

// End ifndef::EAPCDRelease[]
endif::[]

//*****************************************************************************
// Begin CD release Product instructions
//*****************************************************************************
ifdef::EAPCDRelease[]

[[introduction]]
== Introduction

These quickstarts run on {productNameFull} {productVersion}. Each quickstart folder contains a `README{outfilesuffix}` file that describes the quickstart features and provides instructions about how to build and run it.

We recommend that you use the *{quickstartDownloadName}* ZIP file, which you can download from the {quickstartDownloadUrl}[{ProductShortName} Software Download] page on the Red Hat Customer Portal. This version of the quickstarts uses the correct dependencies and ensures that you test and compile against the correct server runtime environment.

Make sure you read this entire document before you attempt to work with the quickstarts. It contains the following information:

* xref:suggested_approach_to_the_quickstarts[Suggested Approach to the Quickstarts]: A suggested approach on how to work with the quickstarts.
* xref:getting_started_with_openshift_overview[Getting Started with {xpaasproduct-shortname}]: Information about how to build and deploy applications to {xpaasproduct-shortname}.
* https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONTRIBUTING.adoc#jboss_developer_contributing_guide[Contributing Guide]: This document contains information targeted for developers who want to contribute to {productName} developer projects.
* xref:available_quickstarts[Available Quickstarts]: List of the available quickstarts and details about each one.

// Suggested Approach to the Quickstarts
include::shared-doc/suggested-approach.adoc[leveloffset=+1]

// Getting Started with OpenShift
include::shared-doc/cd-openshift-getting-started-overview.adoc[leveloffset=+1]

// Available Quickstarts
include::shared-doc/available-quickstarts.adoc[leveloffset=+1]

// End ifdef::EAPCDRelease[]
endif::[]
