include::../shared-doc/attributes.adoc[]

= temperature-converter: Stateless Session EJB (SLSB)
:author: Bruce Wolfe
:level: Beginner
:technologies: CDI, JSF, SLSB EJB
:openshift: true

[abstract]
The `temperature-converter` quickstart does temperature conversion using an EJB Stateless Session Bean (SLSB), CDI, and a JSF front-end client.

:standalone-server-type: default
:archiveType: war

== What is it?

The `temperature-converter` example demonstrates the use of an EJB Stateless Session Bean (SLSB) and CDI, accessed using a JSF, and deployed to {productNameFull} using a WAR archive.

The application does the following:

. The User Interface is a JSF page that asks for a temperature and a scale (Fahrenheit or Celsius).
. When you click on `Convert`, the temperature string is passed to the TemperatureConverter controller (managed) bean.
. The managed bean then invokes the `convert()` method of the injected TemperatureConvertEJB (notice the field annotated with @Inject).
. The response from TemperatureConvertEJB is stored in the `temperature` field of the managed bean.
. The managed bean is annotated as @SessionScoped, so the same managed bean instance is used for the entire session.

// Link to the quickstart source
include::../shared-doc/view-the-source.adoc[leveloffset=+1]
// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
// Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]

// build and run with standard server distribution
[[build_and_run_the_quickstart_with_server_dist]]
== Building and running the quickstart application with a {productName} server distribution
// Start the {productName} Standalone Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+2]
// Build and Deploy the Quickstart
include::../shared-doc/build-and-deploy-the-quickstart.adoc[leveloffset=+2]

=== Access the Application

The application will be running at the following URL: http://localhost:8080/{artifactId}/.

You will be presented with a simple form for temperature conversion.

. Optionally, Select a scale: Celsius or Fahrenheit.
. Enter a temperature.
. Press the `Convert` button to see the results.

// Server Distribution Testing
include::../shared-doc/run-integration-tests-with-server-distribution.adoc[leveloffset=+2]
// Undeploy the Quickstart
include::../shared-doc/undeploy-the-quickstart.adoc[leveloffset=+2]

// Build and run sections for other environments/builds
ifndef::ProductRelease,EAPXPRelease[]
include::../shared-doc/build-and-run-the-quickstart-with-provisioned-server.adoc[leveloffset=+1]
endif::[]
include::../shared-doc/build-and-run-the-quickstart-with-openshift.adoc[leveloffset=+1]