= ejb-multi-server: EJB Communication Across Servers
:author: Wolf-Dieter Fink
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: Advanced
:technologies: EJB, EAR
:source: {githubRepoUrl}

[abstract]
The `ejb-multi-server` quickstart shows how to communicate between multiple applications deployed to different servers using an EJB to log the invocation.

== What is it?

The `ejb-multi-server` quickstart demonstrates communication between applications deployed to different {productNameFull} servers. Each application is deployed as an EAR and contains a simple EJB bean. The only function of each bean is to log the invocation.

This example consists of the following Maven projects, each with a shared parent:

[cols="40%,60%",options="headers"]
|===
|Sub-project |Description

|`app-main` |An application that can be called by the `client`. It can also call the different sub-applications.
|`app-one` and `app-two` |These are simple applications that contain an EJB sub-project to build the `ejb.jar` file and an EAR sub-project to build the `app.ear` file. Each application contains only one EJB that logs a statement on a method call and returns the `jboss.node.name` and credentials.
|`app-web` |A simple WAR application. It consists of one Servlet that demonstrates how to invoke EJBs on a different server.
|`client` |This project builds the standalone client and executes it.
|===

The root `pom.xml` builds each of the subprojects in an appropriate order.

The server configuration is done using CLI batch scripts located in the root of the quickstart folder.

== System Requirements

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

All you need to build this project is {buildRequirements}. See link:{configureMavenDocUrl}[Configure Maven to Build and Deploy the Quickstarts] to make sure you are configured correctly for testing the quickstarts.

== Start with a Clean Server Install

It is important to start with a clean version of {productName} before testing this quickstart. Be sure to unzip or install a fresh {productName} instance.

== Use of {jbossHomeName}

In the following instructions, replace `__{jbossHomeName}__` with the actual path to your {productName} installation. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of {jbossHomeName} and JBOSS_HOME Variables].

== Add the Application Users

The following users must be added to the `ApplicationRealm` to run this quickstart. Be sure to use the names and passwords specified in the table as they are required to run this example.

[cols="20%,20%,20%,40%",options="headers"]
|===
|UserName |Realm |Password |Roles

|quickuser |ApplicationRealm |quick-123 |_leave blank for none_
|quickuser1 |ApplicationRealm |quick123+ |_leave blank for none_
|quickuser2 |ApplicationRealm |quick+123 |_leave blank for none_
|===

To add the users, open a terminal and type the following commands:

[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/add-user.sh -a -u quickuser -p quick-123
$ __{jbossHomeName}__/bin/add-user.sh -a -u quickuser1 -p quick123+
$ __{jbossHomeName}__/bin/add-user.sh -a -u quickuser2 -p quick+123
----

NOTE: For Windows, use the `__{jbossHomeName}__\bin\add-user.bat` script.

If you prefer, you can use the `add-user` utility interactively. For an example of how to use the add-user utility, see the instructions located here: link:{addApplicationUserDocUrl}[Add an Application User].

== Back Up the Server Configuration Files

The {productName} server configuration for this quickstart is very complicated and not easily restored by running a JBoss CLI script, so it is important to back up your server configuration files before you begin.

. If it is running, stop the {productName} server.
. Back up the following files, replacing __{jbossHomeName}__ with the path to your {productName} installation:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
__{jbossHomeName}__/domain/configuration/domain.xml
__{jbossHomeName}__/domain/configuration/host.xml
----

. After you have completed testing and undeployed this quickstart, you can replace these files to restore the server to its original configuration.

== Configure the Server

You configure the domain server by running JBoss CLI commands. For your convenience, this quickstart batches the commands into a `install-domain.cli` script provided in the root directory of this quickstart.

. Start with a fresh instance of the {productName} as noted above under <<start_with_a_clean_server_install,Start with a Clean {productName} Install>>.

. Be sure you add the required users as specified above under <<add_the_application_users,Add the Application Users>>.

. Before you begin, make sure you followed the instructions above under <<back_up_the_server_configuration_files,Back Up the {productName} Server Configuration Files>>.

. Start the {productName} server
** Open a terminal and navigate to the root of the EAP directory.
** Start the server using the following command:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __EAP_HOME__/bin/domain.sh
----
+
NOTE: For Windows, use the `__EAP_HOME__/bin/domain.bat` script.

. Review the `install-domain.cli` file in the root of this quickstart directory. This script configures and starts multiple servers needed to run this quickstart.
. Open a new terminal, navigate to the root directory of this quickstart, and run the following command, replacing __{jbossHomeName}__ with the path to your server:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh -c --file=install-domain.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

IMPORTANT: Depending on your machine configuration, you might see "Exception in thread "main" java.lang.OutOfMemoryError: unable to create new native thread" exceptions in the server log when you run this script. If you do, you must increase the ulimit open files and max user processes settings. Instructions to do this are located here: http://ithubinfo.blogspot.com/2013/07/how-to-increase-ulimit-open-file-and.html. After you update the ulimit settings, be sure to reboot and start with a fresh instance of the server.

== Review the Modified Server Configuration

There are too many additions to the configuration files to list here. Feel free to compare the `domain.xml` and `host.xml` to the backup copies to see the changes made to configure the server to run this quickstart.

== Build and Deploy the Quickstart

. Make sure you have started and configured the {productName} server successfully as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type this command to build the artifacts:
+
----
$ mvn clean install
----
+
You should see `BUILD SUCCESS` at the end of the build `SUCCESS` messages for each component.

. In the same terminal, deploy the applications using the provided CLI batch script by typing the following command:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh -c --file=deploy-domain.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

IMPORTANT: If ERRORs appear in the `server.log` when installing or deploying the quickstart, stop the domain and restart it. This should ensure further steps run correctly.

== Access the Remote Client Application

This example shows how to invoke an EJB from a remote standalone application.

. Make sure that the deployments are successful as described above.
. Navigate to the quickstart `client/` subdirectory.
. Type this command to run the application:
+
----
$ mvn exec:java
----

. If it is necessary to invoke the client with a different {productName} version the main class can be invoked by using the following command from the root directory of this quickstart. Replace __{jbossHomeName}__ with your current installation path. The output should be similar to the previous mvn executions.
+
[subs=normal]
----
java -cp $ __{jbossHomeName}__/bin/client/jboss-client.jar:app-main/ejb/target/ejb-multi-server-app-main-ejb-client.jar:app-two/ejb/target/ejb-multi-server-app-two-ejb-client.jar:client/target/ejb-multi-server-client.jar org.jboss.as.quickstarts.ejb.multi.server.Client
----

[IMPORTANT]
====
* If `exec` is called multiple times, the invocation for `app1` might use `app-oneA` and `app-oneB` node due to cluster loadbalancing.
* A {productName} will deny the invocation of unsecured methods of `appOne`/`appTwo` since security is enabled but the method does not include `@Roles`. You need to set `default-missing-method-permissions-deny-access = false` for the `ejb3` subsystem within the domain profile `ha` and `default` to allow the method invocation. See the `install-domain.cli` script.
====

== Access the JSF application Inside the Main Application

The JSF example shows different annotations to inject the EJB. Also how to handle the annotation if different beans implement the same interface and therefore the container is not able to decide which bean needs to be injected without additional informations.

. Make sure that the deployments are successful as described above.
. Use a browser to access the JSF application at the following URL: http://localhost:8080/ejb-multi-server-app-main-web/
. Insert a message in the Text input and invoke the different methods. The result is shown in the browser.
. See server logfiles and find your given message logged as INFO.

== Access the Servlet Application Deployed as a WAR Inside a Minimal Server

An example how to access EJBs from a separate instance which only contains a web application.

. Make sure that the deployments are successful as described above.
. Use a browser to access the Servlet at the following URL: http://localhost:8380/ejb-multi-server-app-web/
. The Servlet will invoke the remote EJBs directly and show the results, compare that the invocation is successful

== Undeploy the Archives

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=undeploy-domain.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat`.

== Remove the Server Domain Configuration

. If it is running, stop the {productName} server.
. Restore the `__{jbossHomeName}__/domain/configuration/domain.xml` and `__{jbossHomeName}__/domain/configuration/host.xml` files with the back-up copies of the files. Be sure to replace `__{jbossHomeName}__` with the path to your server.

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

EJB Client (ejb-client) currently has limited support in the Eclipse Web Tools Platform (WTP). For that reason, this quickstart is not supported in Red Hat JBoss Developer Studio.

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

----
$ mvn dependency:sources
----
