include::../shared-doc/attributes.adoc[]

= managed-executor-service: Managed Executor Service example
:author: Rafael Benevides
:level: Beginner
:technologies: EE Concurrency Utilities, JAX-RS, JAX-RS Client API

[abstract]
The `managed-executor-service` quickstart demonstrates how Jakarta EE applications can submit tasks for asynchronous execution.

:standalone-server-type: default
:archiveType: war
:uses-h2:
:uses-ds-xml:

//*************************************************
// Shared CD and Product Release content
//*************************************************

== What is it?

The Managed Executor Service (javax.enterprise.concurrent.ManagedExecutorService) allows Jakarta EE applications to submit tasks for asynchronous execution. It is an extension of Java SE's Executor Service (java.util.concurrent.ExecutorService) adapted to the Jakarta EE platform requirements.

Managed Executor Service instances are managed by the application server, thus Jakarta EE applications are forbidden to invoke any lifecycle related method.

A JAX-RS resource provides access to some operations that are executed asynchronously.

This quickstart does not contain any user interface. The tests must be run to verify everything is working correctly.


//*************************************************
// Product Release content only
//*************************************************

ifndef::EAPCDRelease[]

// Considerations for Use in a Production Environment
include::../shared-doc/development-shortcuts.adoc[leveloffset=+1]
// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
// Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]
// Start the {productName} Standalone Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]
// Run the Arquillian Tests
include::../shared-doc/run-arquillian-tests.adoc[leveloffset=+1]

== Investigate the Console Output

When you run the Arquillian tests, Maven prints summary of the performed tests to the console. You should see the following results.

[source,options="nowrap"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jboss.as.quickstarts.managedexecutorservice.test.ProductsRestClientIT
org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.4.Final
org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.4.Final
org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version 4.0.18.Final
org.jboss.as.quickstarts.managedexecutorservice.test.ProductsRestClientIT testRestResources
INFO: creating a new product
org.jboss.as.quickstarts.managedexecutorservice.test.ProductsRestClientIT testRestResources
INFO: Product created. Executing a long running task
org.jboss.as.quickstarts.managedexecutorservice.test.ProductsRestClientIT testRestResources
INFO: Deleting all products
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.619 sec - in org.jboss.as.quickstarts.managedexecutorservice.test.ProductsRestClientIT

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

== Investigate the Server Console Output

Look at the {productName} console or Server log and you should see log messages like the following:

[source,options="nowrap"]
----
INFO  [ProductResourceRESTService] (default task-51) Will create a new Product on other Thread
INFO  [ProductResourceRESTService] (default task-51) Returning response
INFO  [PersitTask] (EE-ManagedExecutorService-default-Thread-5) Begin transaction
INFO  [PersitTask] (EE-ManagedExecutorService-default-Thread-5) Persisting a new product
INFO  [PersitTask] (EE-ManagedExecutorService-default-Thread-5) Commit transaction
INFO  [ProductResourceRESTService] (default task-52) Submitting a new long running task to be executed
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [LongRunningTask] (EE-ManagedExecutorService-default-Thread-5) Starting a long running task
INFO  [LongRunningTask] (EE-ManagedExecutorService-default-Thread-5) Analysing A Product
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Result is available. Returning result...56
INFO  [ProductResourceRESTService] (default task-53) Will delete all Products on other Thread
INFO  [ProductResourceRESTService] (default task-53) Returning response
INFO  [DeleteTask] (EE-ManagedExecutorService-default-Thread-5) Begin transaction
INFO  [DeleteTask] (EE-ManagedExecutorService-default-Thread-5) Deleting all products
INFO  [DeleteTask] (EE-ManagedExecutorService-default-Thread-5) Commit transaction. Products deleted: 1
----

Note that the PersistTask and DeleteTask were executed after ProductResourceRESTService sends a Response. The only exception is for LongRunningTask where ProductResourceRESTService waits for its response.

== Server Log: Expected Warnings and Errors

You will see the following warnings in the server log. You can ignore these warnings.

[source,options="nowrap"]
----
WFLYJCA0091: -ds.xml file deployments are deprecated. Support may be removed in a future version.

HHH000431: Unable to determine H2 database version, certain features may not work
----

// Run the Quickstart in Red Hat CodeReady Studio or Eclipse
include::../shared-doc/run-the-quickstart-in-jboss-developer-studio.adoc[leveloffset=+1]

// Additional Red Hat CodeReady Studio instructions
To run the tests in {JBDSProductName}, you must first set the active Maven profile in project properties to one of the following:

* `arq-remote`: This setting is used for a remote server. {JBDSProductName} starts the server for you.
* `arq-managed`: This setting is used for a managed server. If you use this setting, you must xref:start_the_eap_standalone_server[start the server] before you run the tests.

Then, to run the tests, right click on the project or individual classes and select *Run As* –> *JUnit Test* in the context menu.

// Debug the Application
include::../shared-doc/debug-the-application.adoc[leveloffset=+1]

endif::[]

//*************************************************
// CD Release content only
//*************************************************

ifdef::EAPCDRelease[]

// Getting Started with OpenShift
include::../shared-doc/cd-openshift-getting-started.adoc[leveloffset=+1]
//Prepare OpenShift for Quickstart Deployment
include::../shared-doc/cd-create-project.adoc[leveloffset=+1]
// Import the Latest {xpaasproduct-shortname} Image Streams and Templates
include::../shared-doc/cd-import-imagestreams-templates.adoc[leveloffset=+1]
// Deploy the {ProductShortName} Source-to-Image (S2I) Quickstart to OpenShift
include::../shared-doc/cd-deploy-project.adoc[leveloffset=+1]
// OpenShift Post Deployment Tasks: This is not currently needed.
// include::../shared-doc/cd-post-deployment-tasks.adoc[leveloffset=+1]

endif::[]
