= managed-executor-service: Managed Executor Service example
:author: Rafael Benevides
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: Beginner
:technologies: EE Concurrency Utilities, JAX-RS, JAX-RS Client API
:source: {githubRepoUrl}

[abstract]
The `managed-executor-service` quickstart demonstrates how Java EE applications can submit tasks for asynchronous execution.

== What is it?

The Managed Executor Service (javax.enterprise.concurrent.ManagedExecutorService) allows Java EE applications to submit tasks for asynchronous execution. It is an extension of Java SE's Executor Service (java.util.concurrent.ExecutorService) adapted to the Java EE platform requirements.

Managed Executor Service instances are managed by the application server, thus Java EE applications are forbidden to invoke any lifecycle related method.

A JAX-RS resource provides access to some operations that are executed asynchronously.

This quickstart does not contain any user interface. The tests must be run to verify everything is working correctly.

//*************************************************
// Add notes about use in a production environment.
//*************************************************
:uses-h2:
:uses-ds-xml:
include::../development-shortcuts.adoc[leveloffset=+1]

== System Requirements

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

All you need to build this project is {buildRequirements}. See link:{configureMavenDocUrl}[Configure Maven to Build and Deploy the Quickstarts] to make sure you are configured correctly for testing the quickstarts.

[[start_the_server]]
== Start the Server

. Open a terminal and navigate to the root of the {productName} directory.
. Start the {productName} server with the default standalone profile by typing the following command.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

== Run the Arquillian Tests

This quickstart provides Arquillian tests. By default, these tests are configured to be skipped as Arquillian tests require the use of a container.

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type the following command to run the test goal with the following profile activated:
+
[source,options="nowrap"]
----
$ mvn clean verify -Parq-remote
----

You can also let Arquillian manage the {productName} server by using the `arq-managed` profile. For more information about how to run the Arquillian tests, see link:{arquillianTestsDocUrl}[Run the Arquillian Tests].

== Investigate the Console Output

[source,options="nowrap"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.jboss.as.quickstarts.managedexecutorservice.test.ProductsRestClientIT
feb. 22, 2017 4:22:22 PM org.xnio.Xnio <clinit>
INFO: XNIO version 3.3.4.Final
feb. 22, 2017 4:22:22 PM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.3.4.Final
feb. 22, 2017 4:22:22 PM org.jboss.remoting3.EndpointImpl <clinit>
INFO: JBoss Remoting version 4.0.18.Final
feb. 22, 2017 4:22:23 PM org.jboss.as.quickstarts.managedexecutorservice.test.ProductsRestClientIT testRestResources
INFO: creating a new product
feb. 22, 2017 4:22:23 PM org.jboss.as.quickstarts.managedexecutorservice.test.ProductsRestClientIT testRestResources
INFO: Product created. Executing a long running task
feb. 22, 2017 4:22:26 PM org.jboss.as.quickstarts.managedexecutorservice.test.ProductsRestClientIT testRestResources
INFO: Deleting all products
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.619 sec - in org.jboss.as.quickstarts.managedexecutorservice.test.ProductsRestClientIT

Results :

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
----

== Investigate the Server Console Output

Look at the {productName} console or Server log and you should see log messages like the following:

[source,options="nowrap"]
----
INFO  [ProductResourceRESTService] (default task-51) Will create a new Product on other Thread
INFO  [ProductResourceRESTService] (default task-51) Returning response
INFO  [PersitTask] (EE-ManagedExecutorService-default-Thread-5) Begin transaction
INFO  [PersitTask] (EE-ManagedExecutorService-default-Thread-5) Persisting a new product
INFO  [PersitTask] (EE-ManagedExecutorService-default-Thread-5) Commit transaction
INFO  [ProductResourceRESTService] (default task-52) Submitting a new long running task to be executed
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [LongRunningTask] (EE-ManagedExecutorService-default-Thread-5) Starting a long running task
INFO  [LongRunningTask] (EE-ManagedExecutorService-default-Thread-5) Analysing A Product
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Waiting for the result to be available...
INFO  [ProductResourceRESTService] (default task-52) Result is available. Returning result...56
INFO  [ProductResourceRESTService] (default task-53) Will delete all Products on other Thread
INFO  [ProductResourceRESTService] (default task-53) Returning response
INFO  [DeleteTask] (EE-ManagedExecutorService-default-Thread-5) Begin transaction
INFO  [DeleteTask] (EE-ManagedExecutorService-default-Thread-5) Deleting all products
INFO  [DeleteTask] (EE-ManagedExecutorService-default-Thread-5) Commit transaction. Products deleted: 1
----

Note that the PersistTask and DeleteTask were executed after ProductResourceRESTService sends a Response. The only exception is for LongRunningTask where ProductResourceRESTService waits for its response.

== Server Log: Expected Warnings and Errors

You will see the following warnings in the server log. You can ignore these warnings.

[source,options="nowrap"]
----
WFLYJCA0091: -ds.xml file deployments are deprecated. Support may be removed in a future version.

HHH000431: Unable to determine H2 database version, certain features may not work
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

To run the tests in Red Hat JBoss Developer Studio, you must first set the active Maven profile in project properties to one of the following:

* `arq-remote`: This setting is used for a remote server. JBoss Developer Studio starts the server for you.
* `arq-managed`: This setting is used for a managed server. If you use this setting, you must xref:start_the_server[start the server] before you run the tests.

Then, to run the tests, right click on the project or individual classes and select *Run As* –> *JUnit Test* in the context menu.

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

[source,options="nowrap"]
----
$ mvn dependency:sources
----
