include::../shared-doc/attributes.adoc[]

= messaging-clustering: Messaging Example that Demonstrates Clustering
:author: Jess Sightler
:level: Intermediate
:technologies: JMS, MDB
:prerequisites: link:helloworld-mdb/README{outfilesuffix}[helloworld-mdb]

[abstract]
The `messaging-clustering` quickstart does not contain any code and instead uses the `helloworld-mdb` quickstart to demonstrate clustering using ActiveMQ Messaging.

:standalone-server-type: full-ha
:archiveType: war
:optional-domain-or-multiple-servers:
:jbds-not-supported:

== What is it?

The `messaging-clustering` quickstart demonstrates the use of clustering with Apache ActiveMQ and {productNameFull}. It uses the link:../helloworld-mdb/README{outfilesuffix}[helloworld-mdb] quickstart for its tests, so there is no code associated with this quickstart. Instructions are provided to run the quickstart on either a standalone server or in a managed domain.

// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
// Use of {jbossHomeName}_1 and {jbossHomeName}_2
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]

== Prerequisites

IMPORTANT: This quickstart depends on the deployment of the `helloworld-mdb` quickstart WAR for its tests. Before you continue, you must build the `helloworld-mdb` quickstart WAR.

Open a terminal and navigate to the root directory of the helloworld-mdb quickstart.
Type this command to build the WAR archive:

[source,options="nowrap"]
----
$ mvn clean install
----

See the `helloworld-mdb` link:../helloworld-mdb/README{outfilesuffix}[helloworld-mdb README] file for further information about this quickstart.

== Configure the Server and Deploy the Quickstart

You can choose to deploy and run this quickstart in a managed domain or on a standalone server. The sections below describe how to configure and start each type of server.

Before you begin:

. If it is running, stop the {productName} server.
. If you plan to test using a standalone server, back up the standalone server configuration file:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
__{jbossHomeName}__/standalone/configuration/standalone-full-ha.xml
----

. If you plan to test using a managed domain, back up the following files:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
__{jbossHomeName}__/domain/configuration/domain.xml
__{jbossHomeName}__/domain/configuration/host.xml
----

After you have completed testing this quickstart, you can replace these files to restore the server to its original configuration.

=== Configure the Server and Deploy the Quickstart to a Managed Domain

You configure the server by running the install-domain.cli script provided in the root directory of this quickstart.

// Start the {productName} Managed Domain
include::../shared-doc/start-the-managed-domain.adoc[leveloffset=+3]

==== Configure the Domain Server and Deploy the Quickstart Using the JBoss CLI

. Review the `install-domain.cli` file in the root of this quickstart directory. This script creates the server group and servers and configures messaging clustering for testing this quickstart. You will note it does the following:

** Stops the servers
** Creates a server-group to test ActiveMQ Clustering
** Adds 2 servers to the server-group
** Configures ActiveMQ clustering in the full-ha profile
** Deploys the `helloworld-mdb.war` archive
** Restarts the servers.
+
NOTE: If your `helloworld-mdb` quickstart is not located at the same level in the file structure as this quickstart, you must modify its path in this script. Find the `NOTE` in the file for instructions.

. Open a terminal, navigate to the root directory of this quickstart, and run the following command to run the script:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=install-domain.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

+
You should see `"outcome" => "success"` for all of the commands.

. Restart the server in a managed domainas described above.

=== Configure the Server and Deploy the Quickstart to a Standalone Server

If you choose to run standalone servers instead of a managed domain, you will need two instances of the application server.
Application server 2 must be started with a port offset parameter provided to the startup script as `-Djboss.socket.binding.port-offset=100`.

Since both application servers must be configured in the same way, you must configure the first server and then clone it.

[[start_the_eap_standalone_server]]
==== Start the Standalone Server Using the Full HA Profile.

. Open a terminal and navigate to the root of the {productName} directory.
. Start the {productName} server with the standalone full HA profile, which supports messaging and high availability, by typing the following command.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh -c standalone-full-ha.xml
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

==== Configure the Standalone Server and Deploy the Quickstart Using the JBoss CLI

. Review the `install-standalone.cli` file in the root of this quickstart directory. This script configures clustering for a standalone server. You will note it does the following:
** Enables console logging. By default, the full HA profile does not log to the console, so this script enables it.
** Enables clustering and sets a cluster password
** Enables clustering in the RemoteConnectionFactory
** Deploys the `helloworld-mdb.war` archive
** Reloads the server configuration
+
NOTE: If your `helloworld-mdb` quickstart is not located at the same level in the file structure as this quickstart, you must modify its path in this script. Find the `NOTE` in the file for instructions.

. Open a terminal, navigate to the root directory of this quickstart, and run the following command to run the script:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}_1__/bin/jboss-cli.sh --connect --file=install-standalone.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}_1\bin\jboss-cli.bat__` script.

You should see `"outcome" => "success"` for all of the commands.

==== Clone the {productName} Directory

After you have successfully configured the server, you must make a copy of this {productName} directory structure to use for the second server.

. Stop the server.
. Make a copy of this {productName} directory structure to use for the second server.
. Remove the following directories from the cloned instance:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
__{jbossHomeName}_2__/standalone/data/activemq/bindings/
__{jbossHomeName}_2__/standalone/data/activemq/journal/
__{jbossHomeName}_2__/standalone/data/activemq/largemessages/
----

[[start_the_eap_standalone_servers]]
==== Start the {productName} Standalone Servers with the Full HA Profile

When you start the servers, you must pass the cluster password on the command line to avoid the warning `AMQ222186: unable to authorise cluster control`.

[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}_1__/bin/standalone.sh -c standalone-full-ha.xml
$ __{jbossHomeName}_2__/bin/standalone.sh -c standalone-full-ha.xml -Djboss.socket.binding.port-offset=100
----

NOTE: For Windows, use the `__{jbossHomeName}_1__\bin\standalone.bat` and `__{jbossHomeName}_2__\bin\standalone.bat` scripts.

== Access the Application

=== Access the Application Running in a Managed Domain

The application will be running at the following URL: http://localhost:9080/helloworld-mdb/HelloWorldMDBServletClient.

It will send some messages to the queue.

To send messages to the topic, use the following URL: http://localhost:9080/helloworld-mdb/HelloWorldMDBServletClient?topic

=== Access the Application Running in a Standalone Server

The application will be running at the following URL: http://localhost:8080/helloworld-mdb/HelloWorldMDBServletClient.

It will send some messages to the queue.

To send messages to the topic, use the following URL: http://localhost:8080/helloworld-mdb/HelloWorldMDBServletClient?topic

== Investigate the Server Console Output

Look at the {productName} server console or log and you should see log messages like the following:

[source,options="nowrap"]
----
[Server:quickstart-messagingcluster-node1] INFO  [class org.jboss.as.quickstarts.mdb.HelloWorldQueueMDB] (Thread-8 (ActiveMQ-client-global-threads-1067469862)) Received Message from queue: This is message 1
[Server:quickstart-messagingcluster-node1] INFO  [class org.jboss.as.quickstarts.mdb.HelloWorldQueueMDB] (Thread-8 (ActiveMQ-client-global-threads-1067469862)) Received Message from queue: This is message 3
[Server:quickstart-messagingcluster-node1] INFO  [class org.jboss.as.quickstarts.mdb.HelloWorldQueueMDB] (Thread-6 (ActiveMQ-client-global-threads-1067469862)) Received Message from queue: This is message 5
[Server:quickstart-messagingcluster-node2] INFO  [class org.jboss.as.quickstarts.mdb.HelloWorldQueueMDB] (Thread-8 (ActiveMQ-client-global-threads-1771031398)) Received Message from queue: This is message 2
[Server:quickstart-messagingcluster-node2] INFO  [class org.jboss.as.quickstarts.mdb.HelloWorldQueueMDB] (Thread-7 (ActiveMQ-client-global-threads-1771031398)) Received Message from queue: This is message 4
----

Note that the logging indicates messages have arrived from both node 1, `quickstart-messagingcluster-node1`, as well as node 2, `quickstart-messagingcluster-node2`.

== Server Log: Expected Warnings and Errors

You will see the following warnings in the server logs. You can ignore these warnings as they are intended for production servers.

[source,options="nowrap"]
----
WARNING [org.jgroups.protocols.UDP] (Thread-0 (ActiveMQ-server-ActiveMQServerImpl::serverUUID=c79278db-56e6-11e5-af50-69dd76236ee8-1573164340)) JGRP000015: the send buffer of socket DatagramSocket was set to 1MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. net.core.wmem_max on Linux)
WARNING [org.jgroups.protocols.UDP] (Thread-0 (ActiveMQ-server-ActiveMQServerImpl::serverUUID=c79278db-56e6-11e5-af50-69dd76236ee8-1573164340)) JGRP000015: the receive buffer of socket DatagramSocket was set to 20MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max receive buffer in the OS correctly (e.g. net.core.rmem_max on Linux)
WARNING [org.jgroups.protocols.UDP] (Thread-0 (ActiveMQ-server-ActiveMQServerImpl::serverUUID=c79278db-56e6-11e5-af50-69dd76236ee8-1573164340)) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max send buffer in the OS correctly (e.g. net.core.wmem_max on Linux)
WARNING [org.jgroups.protocols.UDP] (Thread-0 (ActiveMQ-server-ActiveMQServerImpl::serverUUID=c79278db-56e6-11e5-af50-69dd76236ee8-1573164340)) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB. This might lead to performance problems. Please set your max receive buffer in the OS correctly (e.g. net.core.rmem_max on Linux)
----

After the server has been running for a period of time, you might see the following warnings in the server log, which are followed by a stacktrace. You can ignore these warnings as this is is a known issue and is harmless. See https://issues.jboss.org/browse/JBEAP-794[JBEAP-794] for more information.

[source,options="nowrap"]
----
WARN  [org.infinispan.topology.ClusterTopologyManagerImpl] (transport-thread--p15-t6) ISPN000197: Error updating cluster member list: org.infinispan.util.concurrent.TimeoutException: Replication timeout for <application-name>
----

== Undeploy the Archive

When you are finished testing, use the following instructions to undeploy the quickstart.

=== Undeploy the Quickstart from a Managed Domain

. Make sure you have xref:start_eap_managed_domain[started the {productName} server] in a managed domain as described above.
. Open a terminal, navigate to the root directory of this quickstart, and run the following command to undeploy the helloworld-mdb quickstart:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=undeploy-domain.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

=== Undeploy the Quickstart from a Standalone Server

. Make sure you xref:start_the_eap_standalone_server[start the {productName} server] as described above.
. Open a terminal, navigate to the root directory of this quickstart, and run the following command to undeploy the helloworld-mdb quickstart:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=undeploy-standalone.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

== Remove the Server Configuration

=== Remove the Domain Server Configuration

You can remove the domain configuration by manually restoring the back-up copies the configuration files or by running the JBoss CLI Script.

[[remove_the_domain_server_configuration_manually]]
==== Remove the Domain Server Configuration Manually

IMPORTANT: This method ensures the server is restored to its prior configuration.

. If it is running, stop the {productName} server.
. Restore the `__{jbossHomeName}__/domain/configuration/domain.xml` and `__{jbossHomeName}__/domain/configuration/host.xml` files with the back-up copies of the files. Make sure you replace `__{jbossHomeName}__` with the path to your server.

==== Remove the Domain Server Configuration by Running the JBoss CLI Script

IMPORTANT: This script returns the server to the default configuration, which might not match the server configuration that existed prior to testing this quickstart. If you were not running with the default configuration before testing this quickstart, you should follow the intructions above to xref:remove_the_domain_server_configuration_manually[manually restore the domain configuration] to its previous state.

. Start the {productName} server by typing the following:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=install-domain.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

. Open a new terminal, navigate to the root directory of this quickstart, and run the following command, replacing `__{jbossHomeName}__` with the path to your server.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=remove-domain.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

+
This script removes the server configuration that was done by the `install-domain.cli` script. You should see the following result following the script commands.
+
[source,options="nowrap"]
----
The batch executed successfully
----

[IMPORTANT]
====
If the `:stop-server` command does not complete before the next commands are issued, you might see an error similar to the following:

[source,options="nowrap"]
----
{"JBAS014653: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-1" => "JBAS010977: Server (quickstart-messagingcluster-node1) still running"}}
----

Simply wait a few seconds and run the command a second time.
====

=== Remove the Standalone Server Configuration

You can remove the domain configuration by manually restoring the back-up copies the configuration files or by running the JBoss CLI Script.

[[remove_the_standalone_server_configuration_manually]]
==== Remove the Standalone Server Configuration Manually

IMPORTANT: This method ensures the server is restored to its prior configuration.

. If they are running, stop both {productName} servers.
. Restore the `__{jbossHomeName}_1__/standalone/configuration/standalone-full-ha.xml` file with the back-up copies of the file. Make sure you replace `__{jbossHomeName}_1__` with the path to your server.

==== Remove the Standalone Configuration by Running the JBoss CLI Script

IMPORTANT: This script returns the server to the default configuration, which might not match the server configuration that existed prior to testing this quickstart. If you were not running with the default configuration before testing this quickstart, you should follow the intructions above to xref:remove_the_standalone_server_configuration_manually[manually restore the standalone configuration] to its previous state.

. Start the {productName} server by typing the following:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}_1__/bin/standalone.sh -c standalone-full-ha.xml
----
+
NOTE: For Windows, use the `__{jbossHomeName}_1__\bin\standalone.bat` script.

. Open a new terminal, navigate to the root directory of this quickstart, and run the following command, replacing `__{jbossHomeName}_1__` with the path to your server.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}_1__/bin/jboss-cli.sh --connect --file=remove-standalone.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}_1__\bin\jboss-cli.bat` script.

+
This script removes the server configuration that was done by the `install-standalone.cli` script. You should see the following result following the script commands:
+
[source,options="nowrap"]
----
The batch executed successfully
----

=== Delete the Cloned Standalone {productName} Directory

. If it is running, stop the second instance of the {productName} server.
. Delete the cloned directory.

// Run the Quickstart in Red Hat CodeReady Studio or Eclipse
include::../shared-doc/run-the-quickstart-in-jboss-developer-studio.adoc[leveloffset=+1]
