build:
  uri: https://github.com/wildfly/quickstart.git
  ref: main-no-glow
  contextDir: micrometer
deploy:
  replicas: 1
  env:
    - name: OTEL_COLLECTOR_HOST
      value: "opentelemetrycollector"
