name: WildFly EJB Remote Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - <quickstart-path>/**'
      - .github/workflows/quickstart_ci.yml

jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: ejb-remote
      DEPLOYMENT_DIR: webapp
      TEST_PROVISIONED_SERVER: true
      TEST_BOOTABLE_JAR: true
      TEST_OPENSHIFT: false
      SERVER_PROVISIONING_SERVER_HOST: https://localhost:8443
      MATRIX_JDK: '"17"'
      MATRIX_OS: '"ubuntu-latest"'