= jsonp: JSON-P Object-based JSON generation and Stream-based JSON consuming
:author: Rafael Benevides
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../shared-doc/attributes.adoc[]

:level: Beginner
:technologies: CDI, JSF, JSON-P
:source: {githubRepoUrl}

[abstract]
The `jsonp` quickstart demonstrates how to use the JSON-P API to produce object-based structures and then parse and consume them as stream-based JSON strings.

== What is it?

The `jsonp` quickstart creates a JSON string through object-based JSON generation and then parses and consumes it using stream-based JSON.

It shows how to use the JSON-P API to generate, parse, and consume JSON files.

//*************************************************
// Add System Requirements
//*************************************************
// == System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]

//*************************************************
// Add Use of JBoss Home Name
//*************************************************
// == Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]

//*************************************************
// Start the server with the default profile
//*************************************************
// == Start the Server with the Default Profile
include::../shared-doc/start-server-default-profile.adoc[leveloffset=+1]

== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:
+
[source,options="nowrap"]
----
$ mvn clean package wildfly:deploy
----

. This will deploy `target/{artifactId}` to the running instance of the server.

== Access the Application

Access the running application in a browser at the following URL: http://localhost:8080/{artifactId}/

. You are presented with a simple form that is pre-filled with personal data. You can change those values if you prefer.

. Click on the *Generate JSON String from Personal Data* button. The text area below the button presents a JSON string representing the data and values from the completed form.
+
Note that the JSON string contains String, number, boolean and array values.

. Now, click on the *Parse JSON String using Stream* button. The text area below the button shows the events generated from the parsed JSON string.

== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:
+
[source,options="nowrap"]
----
$ mvn wildfly:undeploy
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.
+
[source,options="nowrap"]
----
$ mvn dependency:sources
----
