include::../shared-doc/attributes.adoc[]

= todo-backend: quickstart for backend deployment on OpenShift
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:keywords:          openshift,galleon,helm
:level:             Intermediate
:technologies:      JPA, JAX-RS, OpenShift, Galleon
:openshift: true

[abstract]
The `todo-backend` quickstart demonstrates how to implement a backend that exposes a HTTP API with JAX-RS
to manage a list of ToDo which are persisted in a database with JPA.

ifndef::ProductRelease[]
This quickstart shows how to setup a local deployment of this backend as well as a deployment on OpenShift to connect
to a PostgreSQL database also hosted on OpenShift.
endif::[]
ifdef::ProductRelease[]
This quickstart shows how to deploy a {productName} application on OpenShift that connects
to a PostgreSQL database also hosted on OpenShift.
endif::[]


== What is it?

The `todo-backend` quickstart demonstrates how to implement a backend that exposes a HTTP API with `JAX-RS`
to manage a list of ToDo which are persisted in a database with `JPA`.

* The backend exposes a HTTP API to manage a list of todos that complies with the specs defined at https://todobackend.com/specs/index.html[todobackend.com].
* It requires a connection to a PostgreSQL database to persist the todos.
ifndef::ProductRelease[]
* It uses the Bootable Jar for local and cloud deployment
endif::[]
* It can be build with {productName} S2I images for cloud deployment
ifndef::ProductRelease,EAPXPRelease[]
* It is deployed on OpenShift using the https://docs.wildfly.org/wildfly-charts/[Helm Chart for {productName}].
endif::[]
ifdef::ProductRelease,EAPXPRelease[]
* It is deployed on OpenShift using the https://jbossas.github.io/eap-charts//[Helm Chart for {productName}].
endif::[]

// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]

== Architecture

ifndef::ProductRelease,EAPXPRelease[]

=== Architecture with Bootable Jar

This backend is built and deployed as Bootable Jar that provisions the {productName} application server and all the feature packs it needs for its features.
The layers are defined in the `pom.xml` file in the `<configuration>` section of the `org.wildfly.plugins:wildfly-jar-maven-plugin` plugin:

[source,xml]
----
<layers>
  <layer>cloud-server</layer>
  <layer>postgresql-datasource</layer>
</layers>
----

The `cloud-server` layer provides everything needed to run the backend on OpenShift. This also includes access to
Jakarta EE APIs such as CDI, JAX-RS, JPA, etc. These two layers comes from the {productName} feature pack provided by the Bootable Jar plugin:

[source,xml]
----
<feature-pack>
  <location>wildfly@maven(org.jboss.universe:community-universe)#${version.server.bootable-jar}</location>
</feature-pack>
----

The `postgresql-datasource` layer provides a JDBC driver and DataSource to connect to a PostgreSQL database. It is not provided
by the {productName} feature pack but by an extra feature pack:

[source,xml]
----
 <feature-pack>
   <groupId>org.wildfly</groupId>
   <artifactId>wildfly-datasources-galleon-pack</artifactId>
   <version>${version.wildfly-datasources-galleon-pack}</version>
 </feature-pack>
----

The Git repository for this feature pack is hosted at https://github.com/wildfly-extras/wildfly-datasources-galleon-pack.
It provides JDBC drivers and datasources for different databases but for this quickstart, we will only need the `postgresql-datasource`.
endif::[]

ifdef::EAPXPRelease[]

=== Architecture with Bootable Jar

This backend is built and deployed as Bootable Jar that provisions the {productName} application server and all the feature packs it needs for its features.
The layers are defined in the `pom.xml` file in the `<configuration>` section of the `org.wildfly.plugins:wildfly-jar-maven-plugin` plugin:

[source,xml]
----
<layers>
  <layer>cloud-server</layer>
  <layer>postgresql-datasource</layer>
</layers>
----

The `cloud-server` layer provides everything needed to run the backend on OpenShift. This also includes access to
Jakarta EE APIs such as CDI, JAX-RS, JPA, etc. These two layers comes from the {productName} feature pack provided by the Bootable Jar plugin:

[source,xml]
----
<feature-pack>
  <location>org.jboss.eap:wildfly-galleon-pack:${version.server.bootable-jar}</location>
</feature-pack>
----

The `postgresql-datasource` layer provides a JDBC driver and DataSource to connect to a PostgreSQL database. It is not provided
by the {productName} feature pack but by an extra feature pack:

[source,xml]
----
 <feature-pack>
   <groupId>org.jboss.eap</groupId>
   <artifactId>eap-datasources-galleon-pack</artifactId>
   <version>${version.eap-datasources-galleon-pack}</version>
 </feature-pack>
----

The Git repository for this feature pack is hosted at https://github.com/jbossas/eap-datasources-galleon-pack.
It provides JDBC drivers and datasources for different databases but for this quickstart, we will only need the `postgresql-datasource`.
endif::[]

=== Architecture with S2I

This backend is built using {productName} S2I Builder and Runtime images. 

ifndef::ProductRelease,EAPXPRelease[]
When the image is built, `org.wildfly.plugins:wildfly-maven-plugin` plugin provisions the {productName} application server and all the feature packs it needs for its features.
The layers are defined in the `pom.xml` file in the `<configuration>` section of the `org.wildfly.plugins:wildfly-maven-plugin` plugin:

[source,xml]
----
<layers>
  <layer>cloud-server</layer>
  <layer>postgresql-datasource</layer>
</layers>
----
endif::[]

ifdef::ProductRelease[]
When the image is built, `org.jboss.eap.plugins:eap-maven-plugin` plugin provisions the {productName} application server and all the feature packs it needs for its features.
The layers are defined in the `pom.xml` file in the `<configuration>` section of the `org.jboss.eap.plugins:eap-maven-plugin` plugin:

[source,xml]
----
<layers>
  <layer>cloud-server</layer>
  <layer>postgresql-datasource</layer>
</layers>
----
endif::[]

ifdef::EAPXPRelease[]
When the image is built, it provisions the {productName} application server and all the feature packs it needs for its features:

[source,yaml]
----
build:
  s2i:
    galleonLayers:
      - cloud-server
      - postgresql-datasource
----
endif::[]

The `cloud-server` layer provides everything needed to run the backend on OpenShift. This also includes access to
Jakarta EE APIs such as CDI, JAX-RS, JPA, etc. These two layers comes from the {productName} feature pack provided in the
{productName} S2I builder image.

ifndef::ProductRelease,EAPXPRelease[]
The `postgresql-datasource` layer provides a JDBC driver and DataSource to connect to a PostgreSQL database. It is also provided by
`org.wildfly:wildfly-datasources-galleon-pack` which is included in the WildFly S2I image.

The Git repository for this feature pack is hosted at https://github.com/wildfly-extras/wildfly-datasources-galleon-pack.
It provides JDBC drivers and datasources for different databases but for this quickstart, we will only need the `postgresql-datasource`.
endif::[]

ifdef::ProductRelease,EAPXPRelease[]
The `postgresql-datasource` layer provides a JDBC driver and DataSource to connect to a PostgreSQL database. It is also provided by
the `org.jboss.eap:eap-datasources-galleon-pack` feature pack.

The Git repository for this feature pack is hosted at https://github.com/jbossas/eap-datasources-galleon-pack.
It provides JDBC drivers and datasources for different databases but for this quickstart, we will only need the `postgresql-datasource`.
endif::[]


=== Connection to the PostgreSQL database

ifndef::ProductRelease,EAPXPRelease[]
As mentioned, the JDBC drivers and datasource configuration that the backend uses to connect to the PostgreSQL database
is provided by the `org.wildfly:wildfly-datasources-galleon-pack` feature pack.
endif::[]
ifdef::ProductRelease,EAPXPRelease[]
As mentioned, the JDBC drivers and datasource configuration that the backend uses to connect to the PostgreSQL database
is provided by the `org.jboss.eap:eap-datasources-galleon-pack` feature pack.
endif::[]

By default, it exposes a single datasource.
In the backend, the name of this datasource is `ToDos` and is specified in the `persistence.xml` to configure JPA:

[source,xml]
----
<persistence-unit name="primary">
  <jta-data-source>java:jboss/datasources/ToDos</jta-data-source>
</persistence-unit>
----

At runtime, we only need a few environment variables to establish the connection from {productName} to the external PostgreSQL database:

* `POSTGRESQL_DATABASE` - the name of the database (that will be called `todos`)
* `POSTGRESQL_SERVICE_HOST` - the host to connect to the database
* `POSTGRESQL_SERVICE_PORT` - The port to connect to the database
* `POSTGRESQL_USER` & `POSTGRESQL_PASSWORD` - the credentials to connect to the database
* `POSTGRESQL_DATASOURCE` - The name of the datasources (as mentioned above, it will be `ToDos`)

=== Filters for Cross-Origin Resource Sharing (CORS)

The Web frontend for this quickstart uses JavaScript calls to query the backend's HTTP API.
We must enable Cross-Origin Resource Sharing (CORS) filters in the `undertow` subsystem of {productName} to allow
these HTTP requests to succeed.

ifndef::ProductRelease[]
==== Configuration with Bootable Jar

As we use Bootable Jar to build the application, we provide a CLI script that contains all the commands to create and configure the CORS filters in Undertow. This script is located in the `src/scripts/cors_filters.cli`.
endif::[]

ifdef::ProductRelease[]
==== Configuration with {productName} S2I

As we use S2I to provision the server and build the application, we provide a CLI script that contains all the commands to create and configure the CORS filters in Undertow. This script is located in the `src/scripts/cors_filters.cli`.
endif::[]

This script is executed at build time and will provide the following HTTP headers to enabled CORS:

* `Access-Control-Allow-Origin: *`
* `Access-Control-Allow-Methods: GET, POST, OPTION, PUT, DELETE, PATCH`
* `Access-Control-Allow-Headers: accept, authorization, content-type, x-requested-with`
* `Access-Control-Allow-Credentials: true`
* `Access-Control-Max-Age: 1`

By default, the backend accepts requests from any origin (`*`). This is only simplicity. It is possible to restrict
the allowed origin using the environment variable `CORS_ORIGIN` at runtime.

ifndef::ProductRelease[]
== Run the Backend Locally as a Bootable Jar

=== Package the Backend as a Bootable Jar

The backend is packaged as a Bootable Jar and configured to be deployable on OpenShift with the Maven Profile `bootable-jar-openshift`:

[source,options="nowrap"]
----
$ mvn clean package -P bootable-jar-openshift
----

=== Run a Local PostgreSQL Database

Before running the backend locally, we need to have a local PostgreSQL database that we can connect to.
We use the `postgresql` docker image to create one:

[source,options="nowrap"]
----
$ docker run --name todo-backend-db \
  -e POSTGRES_USER=todos \
  -e POSTGRES_PASSWORD=mysecretpassword \
  -p 5432:5432 \
  postgres
----

This will create a database named `todos` that we can connect to on `localhost:5432` with the credentials `todos / mysecretpassword`.

=== Run the Bootable Jar Application

With the PostgreSQL database running, we can start the backend by passing the required environment variables to connect to the database:

[source,options="nowrap"]
----
$ POSTGRESQL_DATABASE=todos \
  POSTGRESQL_SERVICE_HOST=localhost \
  POSTGRESQL_SERVICE_PORT=5432 \
  POSTGRESQL_USER=todos \
  POSTGRESQL_PASSWORD=mysecretpassword \
  POSTGRESQL_DATASOURCE=ToDos \
  java -jar target/todo-backend-bootable.jar
...
14:41:58,111 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0010: Deployed "todo-backend.war" (runtime-name : "ROOT.war")
...
----

The backend is running, and we can use the HTTP API to manage a list of todos:

[source,options="nowrap"]
----
# get a list of todos
$ curl http://localhost:8080
[]

# create a todo with the title "This is my first todo item!"
$ curl -X POST -H "Content-Type: application/json"  -d '{"title": "This is my first todo item!"}' http://localhost:8080/
{"completed":false,"id":1,"order":0,"title":"This is my first todo item!","url":"https://localhost:8080/1"}%

# get a list of todos with the one that was just created
$ curl http://localhost:8080
[{"completed":false,"id":1,"order":0,"title":"This is my first todo item!","url":"https://localhost:8080/1"}]
----

== Run the Backend Locally

=== Package the Backend

The backend is packaged and deployed on a provisioned server:

[source,options="nowrap"]
----
$ mvn clean package -Pprovisioned-server
----

[NOTE]
====
To execute the integration tests require *a running PostgreSQL server*. +
If you have already started the PostgreSQL server and want to run the tests you need to execute the following command:

[source,options="nowrap"]
----
$ mvn clean verify -Pprovisioned-server
----
====

=== Run a Local PostgreSQL Database

Before running the backend locally, we need to have a local PostgreSQL database that we can connect to.
We use the `postgresql` docker image to create one:

[source,options="nowrap"]
----
$ docker run --name todo-backend-db \
  -e POSTGRES_USER=todos \
  -e POSTGRES_PASSWORD=mysecretpassword \
  -p 5432:5432 \
  postgres
----

This will create a database named `todos` that we can connect to on `localhost:5432` with the credentials `todos / mysecretpassword`.

=== Run the Application

With the PostgreSQL database running, we can start the backend by passing the required environment variables to connect to the database:

[source,options="nowrap"]
----
$ JBOSS_HOME=./target/server \
  POSTGRESQL_DATABASE=todos \
  POSTGRESQL_SERVICE_HOST=localhost \
  POSTGRESQL_SERVICE_PORT=5432 \
  POSTGRESQL_USER=todos \
  POSTGRESQL_PASSWORD=mysecretpassword \
  POSTGRESQL_DATASOURCE=ToDos \
  ./target/server/bin/standalone.sh
...
14:41:58,111 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0010: Deployed "todo-backend.war" (runtime-name : "todo-backend.war")
...
----

The backend is running, and we can use the HTTP API to manage a list of todos:

[source,options="nowrap"]
----
# get a list of todos
$ curl http://localhost:8080/todo-backend
[]

# create a todo with the title "This is my first todo item!"
$ curl -X POST -H "Content-Type: application/json"  -d '{"title": "This is my first todo item!"}' http://localhost:8080/todo-backend
{"completed":false,"id":1,"order":0,"title":"This is my first todo item!","url":"https://localhost:8080/todo-backend/1"}%

# get a list of todos with the one that was just created
$ curl http://localhost:8080/todo-backend
[{"completed":false,"id":1,"order":0,"title":"This is my first todo item!","url":"https://localhost:8080/todo-backend/1"}]
----

// Run the Arquillian Tests
include::../shared-doc/run-arquillian-functional-tests-remote.adoc[leveloffset=+1]

[NOTE]
====
You may also execute those tests against a running bootable jar application, but you will need to add `-Dserver.host=http://localhost:8080` to the command.
====
endif::[]

== Run the Backend on OpenShift

include::../shared-doc/build-the-quickstart-for-openshift.adoc[leveloffset=+1]

=== Prerequisites

* You must be logged in OpenShift and have an `oc` client to connect to OpenShift
* https://helm.sh[Helm] must be installed to deploy the backend on OpenShift.

Once you have installed Helm, you need to add the repository that provides Helm Charts for {productName}:

ifndef::ProductRelease,EAPXPRelease[]
[source,options="nowrap"]
----
$ helm repo add wildfly https://docs.wildfly.org/wildfly-charts/
"wildfly" has been added to your repositories
$ helm search repo wildfly
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
wildfly/wildfly         ...             ...            Build and Deploy WildFly applications on OpenShift
wildfly/wildfly-common  ...             ...            A library chart for WildFly-based applications
----
endif::[]
ifdef::ProductRelease,EAPXPRelease[]
[source,options="nowrap",subs="+attributes"]]
----
$ helm repo add jboss-eap https://jbossas.github.io/eap-charts/
"jboss-eap" has been added to your repositories
$ helm search repo jboss-eap
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
{helmChartName}         ...             ...             A Helm chart to build and deploy {productVersion} applications
----
endif::[]

ifndef::ProductRelease[]
=== Build and Deploy the Backend on OpenShift with Bootable Jar
endif::[]

==== Deploy a PostgreSQL Database on OpenShift

[source,options="nowrap"]
----
$ oc new-app postgresql-ephemeral \
   -p DATABASE_SERVICE_NAME=todo-backend-db \
   -p POSTGRESQL_DATABASE=todos
----

This will create a PostgreSQL database named `todos` on OpenShift that can be accessed on the port `5432` on the service `todo-backend-db`.
We don't need to copy the credentials to connect to the database as we will retrieve them later using the `todo-backend-db` secret that was created
when the database is deployed.

ifndef::ProductRelease,EAPXPRelease[]
==== Build and Deploy the Backend on OpenShift with Bootable Jar using the Helm Chart

The backend will be built and deployed on OpenShift with a Helm Chart for {productName}.

[source,options="nowrap",subs="+attributes"]
----
$ helm install todo-backend --set build.ref={WildFlyQuickStartRepoTag} -f https://raw.githubusercontent.com/wildfly/wildfly-charts/main/examples/todo-backend/todo-backend-bootable-jar.yaml {helmChartName}
NAME: todo-backend
...
STATUS: deployed
REVISION: 1
----

The Helm Chart for this quickstart contains all the information to build an image from the source code using Bootable Jar:

[source,options="nowrap"]
----
build:
  uri: https://github.com/wildfly/quickstart.git
  mode: bootable-jar
----
endif::[]

ifdef::EAPXPRelease[]
The backend will be built and deployed on OpenShift with a Helm Chart for {productName}.

[source,options="nowrap",subs="+attributes"]
----
$ helm install todo-backend --set build.ref={EAPQuickstartRepoTag} -f https://raw.githubusercontent.com/jbossas/eap-charts/main/examples/eap-xp3/todo-backend/todo-backend-bootable-jar.yaml {helmChartName}
NAME: todo-backend
...
STATUS: deployed
REVISION: 1
----

The Helm Chart for this quickstart contains all the information to build an image from the source code using Bootable Jar:

[source,options="nowrap"]
----
build:
  uri: https://github.com/jboss-developer/jboss-eap-quickstarts.git
  mode: bootable-jar
----
endif::[]

ifndef::ProductRelease[]

This will create a new deployment on OpenShift and deploy the application.

If you want to see all the configuration elements to customize your deployment you can use the following command:
[source,options="nowrap",subs="+attributes"]
----
$ helm show readme {helmChartName}
----

Let’s wait for the application to be built and deployed:
[source,options="nowrap",subs="+attributes"]
----
$ oc get deployment {artifactId} -w
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
{artifactId}   0/1     1            0           31s
...
{artifactId}   1/1     1            1           4m31s
----

endif::[]

ifndef::ProductRelease[]
=== Build and Deploy the Backend on OpenShift with {productName} S2I
endif::[]

The backend will be built and deployed on OpenShift with a Helm Chart for {productName}.

ifdef::EAPXPRelease[]
==== Deploy a PostgreSQL Database on OpenShift

[source,options="nowrap"]
----
$ oc new-app postgresql-ephemeral \
   -p DATABASE_SERVICE_NAME=todo-backend-db \
   -p POSTGRESQL_DATABASE=todos
----

This will create a PostgreSQL database named `todos` on OpenShift that can be accessed on the port `5432` on the service `todo-backend-db`.
We don't need to copy the credentials to connect to the database as we will retrieve them later using the `todo-backend-db` secret that was created
when the database is deployed.
endif::[]

ifndef::ProductRelease,EAPXPRelease[]
Add the bitnami repository which provides an helm chart for PostgreSQL:
[source,options="nowrap"]
----
$ helm repo add bitnami https://charts.bitnami.com/bitnami
"bitnami" has been added to your repositories
----

Install the full application (database + backend).

[source,options="nowrap",subs="+attributes"]
----
$ helm dependency update todo-backend-chart/
$ helm install todo-backend todo-backend-chart/
NAME: todo-backend
...
STATUS: deployed
REVISION: 1
----
endif::[]

ifndef::ProductRelease,EAPXPRelease[]
The Helm Chart for this quickstart contains all the information to build an image from the source code using S2I and install it with the database:

[source,options="nowrap"]
----
dependencies:
    - name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: ...
    - name: wildfly
      repository: http://docs.wildfly.org/wildfly-charts/
      version: ...
----

endif::[]

ifndef::ProductRelease,EAPXPRelease[]
Any configuration specified by this chart is described in its README that is displayed in OpenShift Dev console
or using the command:

[source,options="nowrap",subs="+attributes"]
----
$ helm show readme {helmChartName}
----

Let's wait for the application to be built and deployed:

[source,options="nowrap",subs="+attributes"]
----
$ oc get deployment todo-backend -w
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
{artifactId}   0/1     1            0           31s
...
{artifactId}   1/1     1            1           4m31s
----

endif::[]

ifdef::ProductRelease,EAPXPRelease[]

//Prepare Helm for Quickstart Deployment
include::../shared-doc/helm-deploy-project.adoc[leveloffset=+1]

endif::[]

=== Environment variables for PostgreSQL

The Helm Chart also contains the environment variables required to connect to the PostgreSQL database.

ifndef::ProductRelease[]
In local deployment the credentials were passed directly as the values of the environment variables.
endif::[]

For OpenShift, we rely on secrets so that the credentials are never copied outside OpenShift:

[source,options="nowrap"]
----
deploy:
  env:
    - name: POSTGRESQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: todo-backend-db
----

When the application is deployed, the value for the `POSTGRESQL_PASSWORD` will be taken from the key `database-password`
in the secret `todo-backend-db`.

// Testing on Openshift
include::../shared-doc/run-arquillian-integration-tests-with-openshift.adoc[leveloffset=+2]

=== Use the todobackend Web Frontend

Once the backend is deployed on OpenShift, it can be accessed from the route `todo-backend`.
Let's find the host that we can use to connect to this backend:

[source,options="nowrap"]
----
$ oc get route todo-backend -o jsonpath="{.spec.host}"
todo-backend-jmesnil1-dev.apps.sandbox.x8i5.p1.openshiftapps.com
----

This value will be different for every installation of the backend.

[WARNING]
====
Make sure to prepend the host with `https://` to be able to connect to the backend from the ToDo Backend Specs or Client.
The host must also be publicly accessible.
====

We can verify that this application is properly working as a ToDo Backend by running its https://todobackend.com/specs/index.html[specs] on it.


Once all tests passed, we can use the https://todobackend.com/client/index.html[todobackend client] to have a Web application connected to the backend.

[NOTE]
====
https://todobackend.com/[todobackend.com] is an external service used to showcase this quickstart.
It might not always be functional but does not impact the availability of this backend.
====

=== Clean Up

==== Remove the Backend

The backend can be deleted from OpenShift by running the command:

[source,options="nowrap"]
----
$ helm uninstall todo-backend
release "todo-backend" uninstalled
----

==== Remove the Database

The PostresSQL database can be deleted from OpenShift by running the commands:

[source,options="nowrap"]
----
$ oc delete all -l template=postgresql-ephemeral-template
replicationcontroller "todo-backend-db-1" deleted
service "todo-backend-db" deleted
deploymentconfig.apps.openshift.io "todo-backend-db" deleted
$ oc delete secret todo-backend-db
secret "todo-backend-db" deleted
----

== Conclusion

This quickstart shows how the datasource feature pack provided by {productName} simplifies the deployment
of a {productName} Jakarta EE backend on OpenShift to connect to an external database and exposes an HTTP API.

ifndef::ProductRelease[]
The use of a Bootable Jar deployment makes it seamless to move from a local deployment for development to a
deployment on OpenShift.
endif::[]