apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  labels:
    app: postgres
data:
  POSTGRES_DB: {{ .Values.db.database }}
  POSTGRES_USER: {{ .Values.db.username }}
  POSTGRES_PASSWORD: {{ .Values.db.password }}
  PGDATA: /var/lib/postgresql/data/pgdata