include::../shared-doc/attributes.adoc[]

= kitchensink-angularjs: Demonstrates AngularJS with JAX-RS
:author: Pete Muir
:level: Intermediate
:technologies: AngularJS, CDI, JPA, EJB, JPA, JAX-RS, BV
:openshift: true

[abstract]
The `kitchensink-angularjs` quickstart demonstrates a {javaVersion} application using AngularJS with JAX-RS, CDI, EJB, JPA, and Bean Validation.

:standalone-server-type: default
:archiveType: war

== What is it?

The `kitchensink-angularjs` quickstart is a deployable Maven 3 project to help you get your foot in the door developing with AngularJS on {javaVersion} with {productNameFull}.

This project is setup to allow you to create a compliant {javaVersion} application using CDI 1.2, EJB 3.2, JPA 2.1 and Bean Validation 1.1. It includes a persistence unit and some sample persistence and transaction code to introduce you to database access in enterprise Java.

//*************************************************
// Product Release content only
//*************************************************

ifndef::EAPCDRelease[]

// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
// Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]
// Start the {productName} Standalone Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]
// Build and Deploy the Quickstart
include::../shared-doc/build-and-deploy-the-quickstart.adoc[leveloffset=+1]

== Access the Application

The application will be running at the following URL: http://localhost:8080/{artifactId}/.

// Undeploy the Quickstart
include::../shared-doc/undeploy-the-quickstart.adoc[leveloffset=+1]
// Run the Arquillian Tests
include::../shared-doc/run-arquillian-tests.adoc[leveloffset=+1]
// Run the Arquillian Functional Tests
include::../shared-doc/run-arquillian-functional-tests.adoc[leveloffset=+1]
// Run the Quickstart in Red Hat CodeReady Studio or Eclipse
include::../shared-doc/run-the-quickstart-in-jboss-developer-studio.adoc[leveloffset=+1]

// Additional Red Hat CodeReady Studio instructions
NOTE: If you have not installed the https://github.com/angelozerr/angularjs-eclipse[AngularJS Eclipse plugin] into {JBDSProductName}, you may see one or more of the following warnings when you import this project. You can ignore these warnings.

[source,options="nowrap"]
----
HTML Problem: Undefined attribute name (ng-app)
HTML Problem: Undefined attribute name (ng-click)
HTML Problem: Undefined attribute name (ng-disabled)
HTML Problem: Undefined attribute name (ng-hide)
HTML Problem: Undefined attribute name (ng-model)
HTML Problem: Undefined attribute name (ng-pattern)
HTML Problem: Undefined attribute name (ng-repeat)
HTML Problem: Undefined attribute name (ng-show)
HTML Problem: Undefined attribute name (ng-submit)
HTML Problem: Undefined attribute name (ng-view)
----

== Debug the Application

If you want to debug the source code or look at the Javadocs of any library in the project, run either of the following commands to pull them into your local repository. The IDE should then detect them.

[source,options="nowrap"]
----
$ mvn dependency:sources
$ mvn dependency:resolve -Dclassifier=javadoc
----

endif::[]

//*************************************************
// Product Release content only
//*************************************************
ifdef::ProductRelease[]

// Getting Started with OpenShift
include::../shared-doc/openshift-getting-started.adoc[leveloffset=+1]
//Prepare OpenShift for Quickstart Deployment
include::../shared-doc/openshift-create-project.adoc[leveloffset=+1]
// Import the Latest {xpaasproduct-shortname} Image Streams and Templates
include::../shared-doc/openshift-import-imagestreams-templates.adoc[leveloffset=+1]
// Deploy the {ProductShortName} Source-to-Image (S2I) Quickstart to OpenShift
include::../shared-doc/openshift-deploy-project.adoc[leveloffset=+1]
// Openshift post deployment tasks
include::../shared-doc/openshift-post-deployment-tasks.adoc[leveloffset=+1]


endif::[]