= kitchensink-angularjs: Demonstrates AngularJS with JAX-RS
:author: Pete Muir
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../shared-doc/attributes.adoc[]

:level: Intermediate
:technologies: AngularJS, CDI, JPA, EJB, JPA, JAX-RS, BV
:source: {githubRepoUrl}

[abstract]
The `kitchensink-angularjs` quickstart demonstrates a Java EE 7 application using AngularJS with JAX-RS, CDI, EJB, JPA, and Bean Validation.

:standalone-server-default:
:archiveType: war

== What is it?

The `kitchensink-angularjs` quickstart is a deployable Maven 3 project to help you get your foot in the door developing with AngularJS on Java EE 7 with {productNameFull}.

This project is setup to allow you to create a compliant Java EE 7 application using CDI 1.2, EJB 3.2, JPA 2.1 and Bean Validation 1.1. It includes a persistence unit and some sample persistence and transaction code to introduce you to database access in enterprise Java.

//*************************************************
// Add System Requirements
//*************************************************
// == System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]

//*************************************************
// Add Use of JBoss Home Name
//*************************************************
// == Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]

//*************************************************
// Start the server with the default profile
//*************************************************
// == Start the {productName} Standalone Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]

//*************************************************
// Build and deploy the quickstart WAR
//*************************************************
// == Build and Deploy the Quickstart
include::../shared-doc/build-and-deploy-the-quickstart.adoc[leveloffset=+1]


== Access the Application

The application will be running at the following URL: http://localhost:8080/{artifactId}/.

//*************************************************
// Undeploy the quickstart archive
//*************************************************
// == Undeploy the Quickstart
include::../shared-doc/undeploy-the-quickstart.adoc[leveloffset=+1]


//*************************************************
// Run the Arquillian tests
//*************************************************
// == Run the Arquillian Tests
include::../shared-doc/run-arquillian-tests.adoc[leveloffset=+1]


== Run the Arquillian Functional Tests

This quickstart provides Arquillian functional tests as well. They are located in the functional-tests/ subdirectory under the root directory of this quickstart.
Functional tests verify that your application behaves correctly from the user's point of view. The tests open a browser instance, simulate clicking around the page as a normal user would do, and then close the browser instance.

To run these tests, you must build the main project as described above.

. Open a terminal and navigate to the root directory of this quickstart.
. Build the quickstart WAR using the following command:
+
[source,options="nowrap"]
----
$ mvn clean package
----

. Navigate to the `functional-tests/` directory in this quickstart.

. If you have a running instance of the {productName} server, as described above, run the remote tests by typing the following command:
+
[source,options="nowrap"]
----
$ mvn clean verify -Parq-remote
----

. If you prefer to run the functional tests using managed instance of the {productName} server, meaning the tests will start the server for you, type fhe following command:
+
[source,options="nowrap"]
----
$ mvn clean verify -Parq-managed
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

NOTE: If you have not installed the https://github.com/angelozerr/angularjs-eclipse[AngularJS Eclipse plugin] into JBoss Developer Studio, you may see one or more of the following warnings when you import this project. You can ignore these warnings.

[source,options="nowrap"]
----
HTML Problem: Undefined attribute name (ng-app)
HTML Problem: Undefined attribute name (ng-click)
HTML Problem: Undefined attribute name (ng-disabled)
HTML Problem: Undefined attribute name (ng-hide)
HTML Problem: Undefined attribute name (ng-model)
HTML Problem: Undefined attribute name (ng-pattern)
HTML Problem: Undefined attribute name (ng-repeat)
HTML Problem: Undefined attribute name (ng-show)
HTML Problem: Undefined attribute name (ng-submit)
HTML Problem: Undefined attribute name (ng-view)
----

== Debug the Application

If you want to debug the source code or look at the Javadocs of any library in the project, run either of the following commands to pull them into your local repository. The IDE should then detect them.

[source,options="nowrap"]
----
$ mvn dependency:sources
$ mvn dependency:resolve -Dclassifier=javadoc
----
