BEGIN
INSERT INTO User (ID, USERNAME) VALUES (1, 'jdoe');
INSERT INTO User (ID, USERNAME) VALUES (2, 'emuster');
COMMIT

BEGIN
INSERT INTO Task (ID, OWNER_ID, TITLE) VALUES (1, 1, 'johns first task');
INSERT INTO Task (ID, OWNER_ID, TITLE) VALUES (2, 1, 'johns second task');
COMMIT