include::../shared-doc/attributes.adoc[]

= helloworld-jms: Helloworld JMS Example
:author: Weston Price
:level: Intermediate
:technologies: JMS

[abstract]
The `helloworld-jms` quickstart demonstrates the use of external JMS clients with {productName}.

:standalone-server-type: full
:archiveType: jar
:restoreScriptName: remove-jms.cli
:app-user-groups: guest

== What is it?

The `helloworld-jms` quickstart demonstrates the use of external JMS clients with {productNameFull}.

It contains the following:

. A message producer that sends messages to a JMS destination deployed to a {productName} server.

. A message consumer that receives message from a JMS destination deployed to a {productName} server.

// Link to the quickstart source
include::../shared-doc/view-the-source.adoc[leveloffset=+1]
// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
// Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]
// Add the Authorized Application User
include::../shared-doc/add-application-user.adoc[leveloffset=+1]
// Back Up the {productName} Standalone Server Configuration
include::../shared-doc/back-up-server-standalone-configuration.adoc[leveloffset=+1]
// Start the {productName} Standalone Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]

[[configure_the_server]]
== Configure the Server

You configure the JMS `test` queue by running JBoss CLI commands. For your convenience, this quickstart batches the commands into a `configure-jms.cli` script provided in the root directory of this quickstart.

. Before you begin, make sure you do the following:

* xref:back_up_standalone_server_configuration[Back up the {productName} standalone server configuration] as described above.
* xref:start_the_eap_standalone_server[Start the {productName} server with the standalone full profile] as described above.

. Review the `configure-jms.cli` file in the `src/main/scripts/` folder of this quickstart directory. This script adds the `test` queue to the `messaging` subsystem in the server configuration file.
. Open a new terminal, navigate to the root directory of this quickstart, and run the following command, replacing __{jbossHomeName}__ with the path to your server:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=configure-jms.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

. You should see the following result when you run the script:
+
[source,options="nowrap"]
----
The batch executed successfully
----

. Stop the {productName} server.

== Review the Modified Server Configuration

After stopping the server, open the `__{jbossHomeName}__/standalone/configuration/standalone-full.xml` file and review the changes.

The following `testQueue` jms-queue was configured in the default server configuration of the `messaging-activemq` subsystem.

[source,xml,options="nowrap"]
----
<jms-queue name="testQueue" entries="queue/test java:jboss/exported/jms/queue/test"/>
----


// Server Distribution Testing
include::../shared-doc/run-integration-tests-with-server-distribution.adoc[leveloffset=+1]


=== Investigate the Console Output

If the Maven command is successful, with the default configuration you will see output similar to this:

[source,options="nowrap"]
----
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Attempting to acquire connection factory "jms/RemoteConnectionFactory"
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Found connection factory "jms/RemoteConnectionFactory" in JNDI
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Attempting to acquire destination "jms/queue/test"
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Found destination "jms/queue/test" in JNDI
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Sending 1 messages with content: Hello, World!
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Received message with content Hello, World!
----

=== Optional Properties

The example provides for a certain amount of customization for the integration test using the system properties.

[cols="20%,30%,50%",options="headers"]
|===
| Property
| Default value
| Description

| username
| quickstartUser
| This `username` is used for both the JMS connection and the JNDI look up. Instructions to set up the quickstart application user can be found here: link:{addApplicationUserDocUrl}[Add an Application User].

| password
| quickstartPwd1!
| This `password` is used for both the JMS connection and the JNDI look up. Instructions to set up the quickstart application user can be found here: link:{addApplicationUserDocUrl}[Add an Application User]

| connection.factory
| jms/RemoteConnectionFactory
| The name of the JMS `ConnectionFactory` you want to use.

| destination
| jms/queue/test
| The name of the JMS `Destination` you want to use.

| message.count
| 1
| The number of JMS messages you want to produce and consume.

| message.content
| "Hello, World!"
| The content of the JMS `TextMessage`.

| java.naming.provider.url
| "http-remoting://127.0.0.1:8080"
| This property allows configuration of the JNDI directory used to look up the JMS destination. This is useful when the client resides on another host.
|===

// Restore the {productName} Standalone Server Configuration
include::../shared-doc/restore-standalone-server-configuration.adoc[leveloffset=+1]

// Additional information about this script
This script removes the `test` queue from the `messaging` subsystem in the server configuration. You should see the following result when you run the script.

[source,options="nowrap"]
----
The batch executed successfully
----

include::../shared-doc/openshift-incompatibility.adoc[leveloffset=+1]