= helloworld-jms: Helloworld JMS Example
:author: Weston Price
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../shared-doc/attributes.adoc[]

:level: Intermediate
:technologies: JMS
:source: {githubRepoUrl}

[abstract]
The `helloworld-jms` quickstart demonstrates the use of external JMS clients with {productName}.

== What is it?

The `helloworld-jms` quickstart demonstrates the use of external JMS clients with {productNameFull}.

It contains the following:

. A message producer that sends messages to a JMS destination deployed to a {productName} server.

. A message consumer that receives message from a JMS destination deployed to a {productName} server.

//*************************************************
// Add System Requirements
//*************************************************
// == System Requirements
:includes-cli-scripts:
include::../shared-doc/system-requirements.adoc[leveloffset=+1]

//*************************************************
// Add Use of JBoss Home Name
//*************************************************
// == Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]

[[add_an_application_user]]
== Add an Application User

This quickstart uses secured management interfaces and requires that you create the following application user to access the running application.

[cols="20%,20%,20%,40%",options="headers"]
|===
|UserName |Realm |Password |Roles

|quickstartUser |ApplicationRealm |quickstartPwd1! |guest
|===

To add the application user, open a terminal and type the following command:

[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/add-user.sh -a -u 'quickstartUser' -p 'quickstartPwd1!' -g 'guest'
----
NOTE: For Windows, use the `__{jbossHomeName}__\bin\add-user.bat` script.

If you prefer, you can use the `add-user` utility interactively.
For an example of how to use the add-user utility, see the instructions located here: link:{addApplicationUserDocUrl}[Add an Application User].

[[configure_the_server]]
== Configure the Server

You configure the JMS `test` queue by running JBoss CLI commands. For your convenience, this quickstart batches the commands into a `configure-jms.cli` script provided in the root directory of this quickstart.

. Before you begin, back up your server configuration file
** If it is running, stop the {productName} server.
** Back up the file: `{jbossHomeName}/standalone/configuration/standalone-full.xml`
** After you have completed testing this quickstart, you can replace this file to restore the server to its original configuration.
. Start the {productName} server with the standalone full profile by typing the following command.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh -c standalone-full.xml
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

. Review the `configure-jms.cli` file in the root of this quickstart directory. This script adds the `test` queue to the `messaging` subsystem in the server configuration file.
. Open a new terminal, navigate to the root directory of this quickstart, and run the following command, replacing {jbossHomeName} with the path to your server:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=configure-jms.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

. You should see the following result when you run the script:
+
----
The batch executed successfully
----

. Stop the {productName} server.

== Review the Modified Server Configuration

After stopping the server, open the `__{jbossHomeName}__/standalone/configuration/standalone-full.xml` file and review the changes.

The following `testQueue` jms-queue was configured in the default server configuration of the `messaging-activemq` subsystem.

[source,xml,options="nowrap"]
----
<jms-queue name="testQueue" entries="queue/test java:jboss/exported/jms/queue/test"/>
----

== Start the Server with the Full Profile

. Open a terminal and navigate to the root of the {productName} directory.
. Start the {productName} server with the standalone full profile by typing the following command:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh -c standalone-full.xml
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

== Build and Execute the Quickstart

To run the quickstart from the command line:

. Make sure you have started the {productName} server. See the instructions in the previous section.

. Open a terminal and navigate to the root of the helloworld-jms quickstart directory:
+
[source,options="nowrap"]
----
$ cd PATH_TO_QUICKSTARTS/helloworld-jms
----

. Type the following command to compile and execute the quickstart:
+
[source,options="nowrap"]
----
$ mvn clean compile exec:java
----

[NOTE]
====
If you execute this command multiple times, you may see the following warning and exception, followed by a stacktrace. This is caused by a bug in Artemis that has been fixed, but not yet released. For details, see https://issues.apache.org/jira/browse/ARTEMIS-158. You can ignore this warning._

----
WARN: AMQ212007: connector.create or connectorFactory.createConnector should never throw an exception, implementation is badly behaved, but we will deal with it anyway.
java.lang.IllegalArgumentException: port out of range:-1
----
====

== Investigate the Console Output

If the Maven command is successful, with the default configuration you will see output similar to this:

[source,options="nowrap"]
----
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Attempting to acquire connection factory "jms/RemoteConnectionFactory"
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Found connection factory "jms/RemoteConnectionFactory" in JNDI
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Attempting to acquire destination "jms/queue/test"
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Found destination "jms/queue/test" in JNDI
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Sending 1 messages with content: Hello, World!
timestamp org.jboss.as.quickstarts.jms.HelloWorldJMSClient main
INFO: Received message with content Hello, World!
----

== Optional Properties

The example provides for a certain amount of customization for the `mvn:exec` plug-in using the system properties.

[cols="30%,70%",options="headers"]
|===
| Property
| Description

| username
| This `username` is used for both the JMS connection and the JNDI look up. Instructions to set up the quickstart application user can be found here: link:{addApplicationUserDocUrl}[Add an Application User].

| password
| This `password` is used for both the JMS connection and the JNDI look up. Instructions to set up the quickstart application user can be found here: link:{addApplicationUserDocUrl}[Add an Application User]

| connection.factory
| The name of the JMS `ConnectionFactory` you want to use.

| destination
| The name of the JMS `Destination` you want to use.

| message.count
| The number of JMS messages you want to produce and consume.

| message.content
| The content of the JMS `TextMessage`.

| java.naming.provider.url
| This property allows configuration of the JNDI directory used to look up the JMS destination. This is useful when the client resides on another host.
|===

[[remove_the_jms_configuration]]
== Remove the JMS Configuration

You can remove the JMS configuration by running the `remove-jms.cli` script provided in the root directory of this quickstart or by manually restoring the back-up copy the configuration file.

=== Remove the JMS Configuration by Running the JBoss CLI Script

. Start the {productName} server with the standalone full profile by typing the following command.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh -c standalone-full.xml
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

. Open a new terminal, navigate to the root directory of this quickstart, and run the following command, replacing {jbossHomeName} with the path to your server.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=remove-jms.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

. This script removes the `test` queue from the `messaging` subsystem in the server configuration. You should see the following result when you run the script.
+
[source,options="nowrap"]
----
The batch executed successfully
----

=== Remove the JMS Configuration Manually

. If it is running, stop the {productName} server.
. Replace the `__{jbossHomeName}__/standalone/configuration/standalone-full.xml` file with the back-up copy of the file.

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

This quickstart consists of multiple projects, so it deploys and runs differently in JBoss Developer Studio than the other quickstarts.

. Make sure you xref:add_an_application_user[Add an Application User] as described above.
. Configure and start the {productName} server in Red Hat JBoss Developer Studio:
** Define a server runtime environment that uses the `standalone-full.xml` configuration file.
** Start the server defined in the previous step.
. Outside of JBoss Developer Studio, configure the JMS `test` queue by running the JBoss CLI commands as described above under xref:configure_the_server[Configure the Server].
. In JBoss Developer Studio, right-click on the *{artifactId}* project and choose *Run As* -> *Java Application*. In the *Select Java Application* window, choose *HellowWorldJMSClient - org.jboss.as.quickstarts.jms* and click *OK*. The client output displays in the *Console* window.
The output messages appear in the *Console* window.
. Make sure you xref:remove_the_jms_configuration[Remove the JMS Configuration] when you have completed testing this quickstart.

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

[source,options="nowrap"]
----
$ mvn dependency:sources
----
