[[build_and_run_the_quickstart_with_bootable_jar]]
= Building and running the quickstart application in a bootable JAR

You can package a {productName} server and an application inside a bootable JAR. You can then run the application on a {productName} bare-metal platform or on a {productName} Openshift platform.

You can use the Maven plug-in to build a {productName} bootable JAR, and then you can run the application on a {productName} bare-metal platform. The following example demonstrates a quickstart `pom.xml` file that contains a Maven profile named *bootable-jar*:

[source,xml,subs="attributes+"]
----
      <profile>
          <id>bootable-jar</id>
          <build>
              <plugins>
                  <plugin>
                      <groupId>org.wildfly.plugins</groupId>
                      <artifactId>wildfly-jar-maven-plugin</artifactId>
                      <configuration>
                          <feature-pack-location>wildfly@maven(org.jboss.universe:community-universe)#${version.server}</feature-pack-location>
                          <layers>
ifndef::custom-bootable-jar-layers[]
                              <layer>jaxrs-server</layer>
                              <layer>microprofile-platform</layer>
endif::[]
ifdef::reactive-messaging[]
                              <layer>cloud-server</layer>
                              <layer>h2-default-datasource</layer>
                              <layer>microprofile-reactive-messaging-kafka</layer>
endif::[]
ifdef::microprofile-lra[]
                              <layer>jaxrs-server</layer>
                              <layer>microprofile-lra-coordinator</layer>
                              <layer>microprofile-lra-participant</layer>
endif::[]
                          </layers>
                          <plugin-options>
                              <jboss-fork-embedded>true</jboss-fork-embedded>
                          </plugin-options>
                      </configuration>
                      <executions>
                          <execution>
                              <goals>
                                  <goal>package</goal>
                              </goals>
                          </execution>
                      </executions>
                  </plugin>
              </plugins>
          </build>
      </profile>
----

ifdef::rest-client-qs[]
NOTE: This configuration needs to be added to both the country-server and the country-client modules.
endif::rest-client-qs[]

.Procedure

. Build the quickstart bootable JAR with the following command:
+
[source,subs="attributes+",options="nowrap"]
----
$ mvn clean package -Pbootable-jar
----
+
. Run the quickstart application contained in the bootable JAR:
ifndef::rest-client-qs[]
+
[source,subs="attributes+",options="nowrap"]
----
ifdef::uses-jaeger[]
$ JAEGER_REPORTER_LOG_SPANS=true JAEGER_SAMPLER_TYPE=const JAEGER_SAMPLER_PARAM=1 java -jar target/{artifactId}-bootable.jar
endif::uses-jaeger[]
ifndef::uses-jaeger[]
$ java -jar target/{artifactId}-bootable.jar
endif::uses-jaeger[]
----
endif::rest-client-qs[]
ifdef::rest-client-qs[]
+
*Country server*
+
[source,subs="attributes+",options="nowrap"]
----
$ java -jar country-server/target/country-server-bootable.jar
----
+
*Country client*
+
[source,subs="attributes+",options="nowrap"]
----
$ java -jar country-client/target/country-client-bootable.jar -Djboss.socket.binding.port-offset=100 -Dorg.wildfly.quickstarts.microprofile.rest.client.CountriesServiceClient/mp-rest/url=http://localhost:8080
----
endif::rest-client-qs[]

. You can now interact with the quickstart application.

[NOTE]
====
After the quickstart application is deployed, the bootable JAR includes the application in the root context. Therefore, any URLs related to the application should not have the `/{artifactId}` path segment after `HOST:PORT`.
====

// Bootable Jar Testing with Arquillian
include::../shared-doc/run-integration-tests-with-bootable-jar.adoc[leveloffset=+1]