[[deploy_eap_s2i]]
= Deploy the {ProductShortName} Source-to-Image (S2I) Quickstart to OpenShift

. Create a new OpenShift application using the {xpaasproduct-shortname} image and the quickstart's source code. Use the following command to use the `{ImagePrefixVersion}-basic-s2i` template with the `{artifactId}` source code on GitHub.
+
[options="nowrap",subs="+attributes"]
----
oc new-app --template={ImagePrefixVersion}-basic-s2i {backslash}
 -p IMAGE_STREAM_NAMESPACE="{artifactId}-project" {backslash}
 -p SOURCE_REPOSITORY_URL="{EAPQuickStartRepo}" {backslash}
 -p SOURCE_REPOSITORY_REF="{EAPQuickStartRepoRef}" {backslash}
 -p CONTEXT_DIR="{artifactId}"
----
With respect to the command parameters:
* `--template` The template to use.
* `-p IMAGE_STREAM_NAMESPACE` The latest images streams and templates xref:import_imagestreams_templates[were imported into the project's namespace], so you must specify the namespace of where to find the image stream. This is usually the OpenShift project's name.
* `-p SOURCE_REPOSITORY_URL` The URL to the repository containing the application source code.
* `-p SOURCE_REPOSITORY_REF` The Git repository reference to use for the source code. This can be a Git branch or tag reference.
* `-p CONTEXT_DIR` The directory within the source repository to build.
+
NOTE: A template can specify default values for many template parameters, and you might have to override some, or all, of the defaults. To see template information, including a list of parameters and any default values, use the command `oc describe template __TEMPLATE_NAME__`.

. Retrieve the name of the build configuration.
+
[options="nowrap"]
----
$ oc get bc -o name
----
. Use the name of the build configuration from the previous step to view the Maven progress of the build.
+
[options="nowrap",subs="+quotes"]
----
$ oc logs -f buildconfig/eap-app
----
