[[deploy_the_quickstart_to_openshift_online]]
= Deploy the Quickstart to OpenShift Online

Use these instructions to deploy the quickstart to {OpenShiftOnlineName}. If you do not yet have an OpenShift Online account and are interested in signing up for one, see link:{LinkOpenShiftSignup}[Choose a Plan] in the OpenShift Online documentation located on the Red Hat Customer Portal. For information about running {ProductShortName} on {OpenShiftOnlineName}, see link:{LinkOpenShiftOnlineGuide}[_{EapForOpenshiftOnlineBookName}_], also located on the Red Hat Customer Portal.

[[create_and_deploy_the_quickstart_project]]
== Create and Deploy the Quickstart Project

Follow these instructions to deploy this quickstart to OpenShift Online.

. Browse to OpenShift Online console and login with your credentials.
. On the *View All Projects* or *Welcome to Project* page, click *Create Project*.
. On the *Create Project* page, enter the following information:
+
[source,subs="+quotes,attributes+"]
----
*Name:*  {artifactId}
*Display Name* {artifactId}
*Description:* {artifactId}
----

. Click *Create* to create the project.
. On the *My Projects* page, choose your new *{artifactId}* and click *Browse Catalog*.
. Choose *{OpenShiftTemplateName}* and then click *Next* to view the *Information* page.
. Click *Next* to navigate to the *Configuration* page. . . Enter the following information. You can leave the remaining fields as they are.
+
[source,subs="+quotes,attributes+"]
----
*Add to Project:* {artifactId}
*Application Name:* {artifactId}
*Custom http Route Hostname:* (leave blank)
*Git Repository URL:* {githubRepoUrl}
*Git Reference:* {githubRepoBranch}
*Context directory:* {artifactId}
----

. Click the *Create* button.
. Click on the *Continue to the project overview* link.

* You should see "Build #1 is running ..." with the console log below.
+
[source,subs="+quotes,attributes+"]
----
Cloning ...
Downloading ...
Building ...
Copying ...
Pushing ...
----

* At the end of the build, you should see "Push successful".
* Click *View Full Log* to see the entire log.

. Click the *Overview* tab to see the `{artifactId}` deployment.
. Click on the application URL on the right side of the page to view the running application. It should be in the following pattern:
+
[source,subs="+quotes,attributes+"]
----
http://__APPLICATION_NAME__-__PROJECT_NAME__.__PORT__.__HOST__.openshiftapps.com
----

[[delete_the_quickstart_project]]
== Delete the Quickstart Project

Follow these instructions to delete the project from OpenShift Online.

. Go to the *View All Projects* page and select *Delete Project* from the drop down list to the right of the *{artifactId}* project.
. Type the name of the project to confirm, and then click *Delete*
