[[considerations_for_use_in_a_production_environment]]
= Considerations for Use in a Production Environment

ifdef::uses-h2[]

H2 Database:: This quickstart uses the H2 database included with {productNameFull} {productVersion}. It is a lightweight, relational example datasource that is used for examples only. It is not robust or scalable, is not supported, and should NOT be used in a production environment.

endif::uses-h2[]

ifdef::uses-ds-xml[]

Datasource Configuration File:: This quickstart uses a `*-ds.xml` datasource configuration file for convenience and ease of database configuration. These files are deprecated in {productName} and should not be used in a production environment. Instead, you should configure the datasource using the Management CLI or Management Console. Datasource configuration is documented in the https://access.redhat.com/documentation/en/red-hat-jboss-enterprise-application-platform/[_Configuration Guide_] for {productNameFull}.

endif::uses-ds-xml[]

ifdef::performance-scalability[]

Performance and Scalability:: A Java EE container is designed with robustness in mind, so you should carefully analyze the scalabiltiy, concurrency, and performance needs of your application before taking advantage of these techniques in your own applications.

endif::performance-scalability[]
