[[deploy_helm]]
== Deploy the {ProductShortName} Source-to-Image (S2I) Quickstart to OpenShift with Helm Charts

Log in to your OpenShift instance using the `oc login` command.
The backend will be built and deployed on OpenShift with a Helm Chart for {productName}.

[source,options="nowrap",subs="+attributes"]
----
$ helm install {artifactId} -f charts/helm.yaml wildfly/wildfly
NAME: {artifactId}
...
STATUS: deployed
REVISION: 1
----

The Helm Chart for this quickstart contains all the information to build an image from the source code using S2I on Java 17:

[source,options="nowrap"]
----
build:
  uri: https://github.com/wildfly/quickstart.git
  mode: s2i
  s2i:
    version: latest
    builderImage: quay.io/wildfly/wildfly-s2i-jdk17
    runtimeImage: quay.io/wildfly/wildfly-runtime-jdk17
----

This will create a new deployment on OpenShift and deploy the application.

If you want to see all the configuration elements to cusomize your deployment you can use the following command:
[source,options="nowrap",subs="+attributes"]
----
$ helm show readme wildfly/wildfly
----

Get the URL of the route to the deployement.
+
[options="nowrap"]
----
$ oc get route
----
. Access the application in your web browser using the URL. The URL is the value of the `HOST/PORT` field from previous command's output.
+
[NOTE]
====

For example, to interact with this quickstart , the root of its application URLs should be `https://_HOST_PORT_Value_/`.
====
+


[[undeploy_helm]]
== Undeploy the {ProductShortName} Source-to-Image (S2I) Quickstart to OpenShift with Helm Charts


[source,options="nowrap",subs="+attributes"]
----
$ helm uninstall {artifactId}
----