[[post_deployment]]
= OpenShift Post Deployment Tasks

Depending on your application, you might need to complete some tasks after your OpenShift application has been built and deployed.

Examples of post-deployment tasks include the following:

* Exposing a service so that the application is viewable from outside of OpenShift.
* Scaling your application to a specific number of replicas.

.Procedure

. Get the service name of your application using the following command.
+
[options="nowrap",subs="+quotes"]
----
$ oc get service
----

. *Optional*: Expose the main service as a route so you can access your application from outside of OpenShift. For example, for the previously created application, use the following command to expose the required service and port.
+
[NOTE]
====
If you used a template to create the application, the route might already exist. If it does, continue on to the next step.
====

+
[options="nowrap",subs="+attributes"]
----
$ oc expose service/{ImagePrefixVersion}-basic-app --port=8080
----
+

. Get the URL of the route.
+
[options="nowrap"]
----
$ oc get route
----
. Access the application in your web browser using the URL. The URL is the value of the `HOST/PORT` field from previous command's output.
+
[NOTE]
====

For example, to interact with this quickstart , the root of its application URLs should be `https://_HOST_PORT_Value_/`.
====
+

. Optionally, you can scale up the application instance by running the following command. This command increases the number of replicas to 3.
+
[options="nowrap",subs="+quotes"]
----
$ oc scale deploymentconfig __DEPLOYMENTCONFIG_NAME__ --replicas=3
----
+
For example, for this` quickstart, use the following command to scale up the application.
+
[options="nowrap",subs="+attributes"]
----
$ oc scale deploymentconfig/{ImagePrefixVersion}-basic-app --replicas=3
----
