[[run_the_arquillian_tests]]
= Run the Arquillian Tests

//******************************************************************************
// Use this template if your quickstart requires a normal start of a single
// standalone server.
//
// You can optionally define a `arquillianTestResults` attribute for
// one line of output.
// For example:
//    :arquillianTestResults: Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
//
// NOTE: If you have more complicated output to present, you can still use
// this and add a section following this one to describe the results.
// For example:
//
// == Investigate the Console Output
//
//******************************************************************************

This quickstart provides Arquillian tests. By default, these tests are configured to be skipped since Arquillian tests require the use of a container.

NOTE: The Arquillian tests deploy the application, so make sure you undeploy the quickstart before you begin.

Follow these steps to run the functional tests.

. xref:start_the_eap_standalone_server[Start the {productName} server] as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type the following command to run the `verify` goal with the `arq-remote` profile activated.
+
[source,options="nowrap"]
----
$ mvn clean verify -Parq-remote
----
ifdef::arquillianTestResults[]
You should see the following results:
+
[source,subs=attributes+,options="nowrap"]
----
Results :

{arquillianTestResults}
----
endif::[]

[NOTE]
====
You can also let Arquillian manage the {productName} server by using the `arq-managed` profile, meaning the tests will start the server for you. This profile requires that you provide Arquillian with the location of the {productName} server, either by setting the `JBOSS_HOME` environment variable, or by setting the `jbossHome` property in the `arquillian.xml` file. For more information, see link:{arquillianTestsDocUrl}[Run the Arquillian Tests].
====
