[[run_the_arquillian_functional_tests_on_openshift]]
= Run the Arquillian Functional Tests on OpenShift
//******************************************************************************
// Include this template if your quickstart provides Openshift Arquillian
// functional tests.
//******************************************************************************

This quickstart provides Arquillian functional tests. They are located under the  `src/test/` directory. Functional tests verify that your application behaves correctly from the user's point of view and simulate clicking around the web page as a normal user would do.

NOTE: The Arquillian functional tests expect a deployed application, so make sure you have deployed the quickstart on OpenShift before you begin.

Follow these steps to run the functional tests.


. Obtain the Openshift deployment URL
+
[source,options="nowrap"]
----
$ oc get route
----
. Run the tests. For this type the following command to run the `verify` goal with the `arq-remote` profile activated and the proper URL.
+
[source,options="nowrap",subs="+attributes"]
----
$ mvn clean verify -Parq-remote -Dserver.host=https://$(oc get route {artifactId} --template='{{ .spec.host }}')
----
