[[run_the_arquillian_integration_tests_with_server_distribution]]
= Run the Arquillian Integration Tests
//******************************************************************************
// Include this template if your quickstart provides standard Arquillian
// integration tests.
//******************************************************************************

This quickstart includes Arquillian integration tests. They are located under the  `src/test/` directory. The integration tests verify that the quickstart runs correctly when deployed on the server.

Follow these steps to run the integration tests.

. Make sure you start the {productName} server, as previously described.

. Make sure you build and deploy the quickstart, as previously described.

. Type the following command to run the `verify` goal with the `arq-remote` profile activated.
+
[source,options="nowrap"]
----
$ mvn verify -Parq-remote
----

[NOTE]
====
You may also use the environment variable `SERVER_HOST` or the system property `server.host` to define the target host of the tests.
====