[[run_the_arquillian_functional_tests]]
= Run the Arquillian Functional Tests
//******************************************************************************
// Include this template if your quickstart provides standard Arquillian
// functional tests.
//******************************************************************************

This quickstart provides Arquillian functional tests. They are located under the  `functional-tests/` directory. Functional tests verify that your application behaves correctly from the user's point of view and simulate clicking around the web page as a normal user would do.

NOTE: The Arquillian functional tests deploy the application, so make sure you undeploy the quickstart before you begin.

Follow these steps to run the functional tests.

ifdef::standalone-server-type[]
. xref:start_the_eap_standalone_server[Start the {productName} server] as described above.
endif::[]

ifdef::managed-domain-type[]
. xref:start_the_eap_managed_domain[Start the {productName} server] as described above.
endif::[]

. Build the quickstart archive.
.. Open a terminal and navigate to the root directory of this quickstart.
.. Build the quickstart archive using the following command:
+
[source,options="nowrap"]
----
$ mvn clean package
----
. Navigate to the `functional-tests/` directory in this quickstart.

. Type the following command to run the `verify` goal with the `arq-remote` profile activated.
+
[source,options="nowrap"]
----
$ mvn clean verify -Parq-remote
----

[NOTE]
====
You can also let Arquillian manage the {productName} server by using the `arq-managed` profile, meaning the tests will start the server for you. This profile requires that you provide Arquillian with the location of the {productName} server, either by setting the `JBOSS_HOME` environment variable, or by setting the `jbossHome` property in the `arquillian.xml` file.  For more information, see link:{arquillianTestsDocUrl}[Run the Arquillian Tests].
====
