[[run_the_quickstart_in_jboss_developer_studio_or_eclipse]]
= Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse
//******************************************************************************
// Include this template to provide instructions to run the quickstart
// in JBoss Developer Studio.
//
// If the quickstart is not supported, create the `jbds-not-supported` attribute.
//******************************************************************************
ifdef::jbds-not-supported[]
This quickstart is not supported in Red Hat JBoss Developer Studio.
endif::jbds-not-supported[]

ifndef::jbds-not-supported[]
You can also start the server and deploy the quickstarts or run the Arquillian tests in Red Hat JBoss Developer Studio or from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].
endif::jbds-not-supported[]

// Add additional instructions specific to running this quickstart in an IDE here.
