[[run_the_arquillian_tests]]
= Run the Arquillian Tests
//******************************************************************************
// Include this template if your quickstart provides standard Arquillian tests.
//******************************************************************************

This quickstart provides Arquillian tests. By default, these tests are configured to be skipped since Arquillian tests require the use of a container.

NOTE: The Arquillian tests deploy the application, so make sure you undeploy the quickstart before you begin.

ifdef::arq-prerequisities[]
== Arquillian Tests prerequisities

{arq-prerequisities}
endif::[]

Follow these steps to run the tests.

ifdef::standalone-server-type[]
. xref:start_the_eap_standalone_server[Start the {productName} server] as described above.
endif::[]

ifdef::managed-domain-type[]
. xref:start_the_eap_managed_domain[Start the {productName} server] as described above.
endif::[]

. Open a terminal and navigate to the root directory of this quickstart.
. Type the following command to run the `verify` goal with the `arq-remote` profile activated.
+
[source,options="nowrap"]
----
$ mvn clean verify -Parq-remote
----
ifdef::arquillianTestResults[]
You should see the following results:
+
[source,subs=attributes+,options="nowrap"]
----
Results :

{arquillianTestResults}
----
endif::[]

[NOTE]
====
You can also let Arquillian manage the {productName} server by using the `arq-managed` profile, meaning the tests will start the server for you. This profile requires that you provide Arquillian with the location of the {productName} server, either by setting the `JBOSS_HOME` environment variable, or by setting the `jbossHome` property in the `arquillian.xml` file. For more information, see link:{arquillianTestsDocUrl}[Run the Arquillian Tests].
====
