[[system_requirements]]
= System Requirements
//******************************************************************************
// Include this template to describe the standard system requirements for
// running the quickstarts.
//
// The Forge quickstarts define a `forge-from-scratch` attribute because they
// run entirely in JBoss Developer Studion and have different requirements .
//
// Quickstarts that provide CLI scripts define an `includes-cli-scripts`
// attribute and have additional requirements.
//******************************************************************************

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

ifndef::forge-from-scratch[]
All you need to build this project is {buildRequirements}. See link:{configureMavenDocUrl}[Configure Maven to Build and Deploy the Quickstarts] to make sure you are configured correctly for testing the quickstarts.
endif::[]

ifdef::forge-from-scratch[]
All you need to build this project is {buildForgeRequirements}. These versions of JBoss Developer Studio embed Maven 3.3.3, so you do not need to install it separately.
endif::[]

ifdef::includes-cli-scripts[]
To run these quickstarts with the provided build scripts, you need the {productName} distribution ZIP. For information on how to install and run the {productName} server, see the {LinkGettingStartedGuide}[__{GettingStartedBookName}__].

endif::[]
