ifdef::requires-multiple-servers[]
[[use_of_jboss_home_name]]
= Use of {jbossHomeName}_1 and {jbossHomeName}_2

This quickstart requires that you clone your `__{jbossHomeName}__` installation directory and run two servers. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of {jbossHomeName} and JBOSS_HOME Variables].

In the following instructions, replace `{jbossHomeName}_1` with the path to your first {productName} server and replace `{jbossHomeName}_2` with the path to your second cloned {productName} server.
endif::[]

ifdef::optional-domain-or-multiple-servers[]
[[use_of_jboss_home_name]]
= Use of {jbossHomeName}_1 and {jbossHomeName}_2

When deploying this quickstart to a managed domain, replace `__{jbossHomeName}__` with the actual path to your {productName} installation. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of {jbossHomeName} and JBOSS_HOME Variables].

When deploying this quickstart to multiple standalone servers, this quickstart requires that you clone your `__{jbossHomeName}__` installation directory and run two servers. In the following instructions, replace `{jbossHomeName}_1` with the path to your first {productName} server and replace `{jbossHomeName}_2` with the path to your second cloned {productName} server.
endif::[]

ifndef::requires-multiple-servers,optional-domain-or-multiple-servers[]
[[use_of_jboss_home_name]]
= Use of {jbossHomeName}

In the following instructions, replace `__{jbossHomeName}__` with the actual path to your {productName} installation. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of {jbossHomeName} and JBOSS_HOME Variables].
endif::[]
