:strimzi-version: v1beta2
[[install_amq_streams]]
= Install AMQ Streams on Openshift

The functionality of this quickstart depends on a running instance of the
https://access.redhat.com/products/red-hat-amq#streams[AMQ Streams] Operator. AMQ Streams is a Red Hat project based on Apache Kafka. To deploy AMQ Streams in the Openshift environment:

. Log in into the Openshift console as `kubeadmin` user (or any cluster administrator).
. Navigate to `Operators` -> `OperatorHub`.
. Search for `AMQ Streams` - click on the 'Red Hat Integration - AMQ Streams' operator (works with both community and Red Hat).
Install it with the default values.
. Run the following command to set up a Kafka cluster called `my-cluster` in your project:
+
[options="nowrap",subs="+attributes"]
----
$ oc apply -n {artifactId}-project -f - <<EOF
apiVersion: kafka.strimzi.io/{strimzi-version}
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
EOF
----

NOTE: If you see errors along the lines of _no matches for kind "Kafka" in version "kafka.strimzi.io/{strimzi-version}"_, execute the command `oc get crd kafkas.kafka.strimzi.io -o jsonpath="{.spec.versions[*].name}"` and update `apiVersion` to the returned version.


. Next set up a topic called `testing` in the `my-cluster` cluster we created:
+
[options="nowrap",subs="+attributes"]
----
oc apply -n microprofile-reactive-messaging-kafka-project -f - <<EOF
apiVersion: kafka.strimzi.io/{strimzi-version}
kind: KafkaTopic
metadata:
  name: testing
labels:
  strimzi.io/cluster: my-cluster
spec:
  partitions: 3
  replicas: 3
EOF
----
