include::../shared-doc/attributes.adoc[]

= deltaspike-projectstage: Demonstrate usage of DeltaSpike project stage and shows usage of a conditional @Exclude
:author: Rafael Benevides
:level: Beginner
:technologies: JSF, CDI, Deltaspike

[abstract]
Demonstrate usage of DeltaSpike project stage and shows usage of a conditional @Exclude

== What is it?

Project stages provide a way to customize the implementation based on the type of deployment environment. For example, you may want to generate sample data for system testing, but not for production. You can create a bean that generates sample data and activate it only for project stage _SystemTest_

_Besides custom project stages_ it's possible to use the following pre-defined project stages:

* UnitTest
* Development
* SystemTest
* IntegrationTest
* Staging
* Production

Furthermore, with `@Exclude`, it is possible to annotate beans which should be ignored by CDI, even if they are in a CDI enabled archive.

This project has a interface called `MyBean` that has 4 different implementations:

* ExcludedExceptOnDevelopment - Uses the annotation `@Exclude(exceptIfProjectStage=Development.class)` to exclude the implementation if the project stage is anything other than Development..
* ExcludedOnDevelopment - Uses the annotation `@Exclude(ifProjectStage=Development.class)` to exclude the implementation for project stage Development.
* MyExcludedBean - Uses the annotation `@Exclude` to exclude the implementation for all project stages.
* NoExcludedBean - The implementation is always available because this bean does not use any annotation.

// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
// Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]
// Start the Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]
//  Run the Arquillian Tests
include::../shared-doc/run-arquillian-tests.adoc[leveloffset=+1]

// Build and Deploy the Quickstart
include::../shared-doc/build-and-deploy-the-quickstart.adoc[leveloffset=+1]

== Access the application

The application will be running at the following URL: http://localhost:8080/{artifactId}/.

You are presented with a simple page that shows the current project stage: _Staging_. You will also see the _List of available CDI instances for MyBean_ table with two available implementations.

Edit the file `src/main/resources/META-INF/apache-deltaspike.properties` and change the `org.apache.deltaspike.ProjectStage` property to `Development`. Deploy the application again

[source,options="nowrap"]
----
$ mvn clean package wildfly:deploy
----

Access the application again at the same URL: http://localhost:8080/wildfly-deltaspike-projectstage[http://localhost:8080/wildfly-deltaspike-projectstage]

Review the _List of available CDI instances for MyBean_ table to verify that the available implementations have changed.

// Undeploy the Quickstart
include::../shared-doc/undeploy-the-quickstart.adoc[leveloffset=+1]
// Run the Quickstart in Red Hat CodeReady Studio or Eclipse
include::../shared-doc/run-the-quickstart-in-jboss-developer-studio.adoc[leveloffset=+1]

== Debug the Application

If you want to debug the source code or look at the Javadocs of any library in the project, run either of the following commands to pull them into your local repository. The IDE should then detect them.

[source,options="nowrap"]
----
$ mvn dependency:sources
$ mvn dependency:resolve -Dclassifier=javadoc
----
