# Default values for todo-backend-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

db:
  username: todos-db
  password: todos-db
  database: todos-db

wildfly:
    build:
      uri: https://github.com/wildfly/quickstart.git
      ref: 38.x
      contextDir: todo-backend
    deploy:
      replicas: 1
      env:
        # Env vars to connect to PostgreSQL DB
        - name: POSTGRESQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_DB
        - name: POSTGRESQL_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_USER
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_PASSWORD
        - name: POSTGRESQL_DATASOURCE
          value: ToDos
        - name: POSTGRESQL_SERVICE_HOST
          value: todo-backend-postgresql
        - name: POSTGRESQL_SERVICE_PORT
          value: "5432"
        # Env to avoid OOME
        - name: GC_MAX_METASPACE_SIZE
          value: "256"
        - name: GC_METASPACE_SIZE
          value: "96"
      initContainers:
        - name: check-db-ready
          image: busybox:1.36
          command: ['sh', '-c',
                    'until nc -z -v -w 2 todo-backend-postgresql 5432; 
                     do echo "waiting for database"; sleep 2; done;']
