= thread-racing: A Java EE thread racing web application
:author: Eduardo Martins
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: Beginner
:technologies: Batch, CDI, EE Concurrency, JAX-RS, JMS, JPA, JSON, Web Sockets
:source: {githubRepoUrl}

[abstract]
A thread racing web application that demonstrates technologies introduced or updated in the latest Java EE specification.

== What is it?

The `thread-racing` quickstart is a web application that demonstrates new and updated technologies introduced by the Java EE 7 specification through simple use cases.

The web application allows the user to trigger a race between 4 threads and follow, in real time, the progress of each thread until the race ends.

The race itself consists of multiple stages, each demonstrating the usage of a specific new or updated Java EE 7 technology:

* Batch 1.0
* EE Concurrency 1.0
* JAX-RS 2.0
* JMS 2.0
* JSON 1.0

WebSockets 1.0 is one of the most relevant new technologies introduced by Java EE 7. Instead of being used in a race stage, a WebSockets 1.0 ServerEndpoint provides the remote application interface.
A new race is run when a client establishes a session. That session is then used to update the client in real time, with respect to the race progress and results. The `src/main/java/org/jboss/as/quickstarts/threadracing/WebSocketRace.java` file is the WebSocket server endpoint class and is a good entry point when studying how the application code works.

JPA 2.1 is also present in the application code. Specifically it is used to store race results in the default data source instance, which is also new to Java EE. Further details are included in the `src/main/java/org/jboss/as/quickstarts/threadracing/results/RaceResults.java` class.

_Note: This quickstart uses the H2 database included with {productNameFull} {productVersion}. It is a lightweight, relational example datasource that is used for examples only. It is not robust or scalable, is not supported, and should NOT be used in a production environment!_

== System Requirements

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

All you need to build this project is {buildRequirements}. See link:{configureMavenDocUrl}[Configure Maven to Build and Deploy the Quickstarts] to make sure you are configured correctly for testing the quickstarts.

== Use of {jbossHomeName}

In the following instructions, replace `__{jbossHomeName}__` with the actual path to your {productName} installation. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of {jbossHomeName} and JBOSS_HOME Variables].

== Start the {productName} Server with the Full Profile

. Open a terminal and navigate to the root of the {productName} directory.
. The following shows the command line to start the server with the full profile:

[subs=normal]
----
For Linux:   $ __{jbossHomeName}__/bin/standalone.sh -c standalone-full.xml
For Windows: __{jbossHomeName}__\bin\standalone.bat -c standalone-full.xml
----

== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:

----
$ mvn clean install wildfly:deploy
----

. This will deploy `target/{artifactId}.war` to the running instance of the server.

== Access the application

The application will be running at the following URL http://localhost:8080/{artifactId}/.

To start a race press the `Insert Coin` button. The page displays the names of the threads as they join the race. It then tracks the progress of each thread through the Batch, EE Concurrency, JAX-RS, JMS, and JSON stages of the race. Finally, it displays the official race results and championship standings.

== Server Log: Expected Warnings and Errors

NOTE: You will see the following warning in the server log. You can ignore this warning.

----
HHH000431: Unable to determine H2 database version, certain features may not work
----

== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a command line and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:

----
$ mvn wildfly:undeploy
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

NOTE: Within JBoss Developer Studio, be sure to define a server runtime environment that uses the `standalone-full.xml` configuration file.

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

----
$ mvn dependency:sources
----