include::../shared-doc/attributes.adoc[]

= helloworld-rf: Helloworld with a JSF (JavaServer Faces) Front End
:author: Brian Leathem
:level: Beginner
:technologies: CDI, JSF, RichFaces

[abstract]
Similar to the `helloworld` quickstart, but with a JSF front end.

:standalone-server-type: default
:archiveType: war

== What is it?

This project demonstrates how to create a {javaVersion} compliant application using JSF 2.2, CDI 1.2, and RichFaces 4.5.

In this example, a standard JSF `h:inputText` component is AJAX enabled using the RichFaces `a4j:ajax tag`. This triggers the application server to re-render only a subsection of the page on a browser event.

// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
// Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]
// Start the {productName} Standalone Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]
// Build and Deploy the Quickstart
include::../shared-doc/build-and-deploy-the-quickstart.adoc[leveloffset=+1]

== Access the application

The application will be running at the following URL: http://localhost:8080/{artifactId}/

// Undeploy the Quickstart
include::../shared-doc/undeploy-the-quickstart.adoc[leveloffset=+1]
// Run the Quickstart in Red Hat CodeReady Studio or Eclipse
include::../shared-doc/run-the-quickstart-in-jboss-developer-studio.adoc[leveloffset=+1]

== Debug the Application

If you want to debug the source code or look at the Javadocs of any library in the project, run either of the following commands to pull them into your local repository. The IDE should then detect them.

[source,options="nowrap"]
----
$ mvn dependency:sources
$ mvn dependency:resolve -Dclassifier=javadoc
----
