= logging-tools: Internationalization and Localization with JBoss Logging Tools
:author: Darrin Mison
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: Beginner
:technologies: JBoss Logging Tools
:source: {githubRepoUrl}

[abstract]
The `logging-tools` quickstart shows how to use JBoss Logging Tools to create internationalized loggers, exceptions, and messages and localize them.

== What is it?

The `logging-tools` quickstart demonstrates the use of JBoss Logging Tools in {productNameFull}. The logging tools create internationalized loggers, exceptions, and generic messages; and then provide localizations for them. This is done using a simple JAX-RS service. Translations in French(fr-FR), German(de-DE), and Swedish (sv-SE) are provided courtesy of http://translate.google.com for demonstration. My apologies if they are less than ideal translations.

Once the quick start is deployed you can access it using URLs documented below.

Instructions are included below for starting {productName} with a different locale than the system default.

== System Requirements

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

All you need to build this project is {buildRequirements}. See link:{configureMavenDocUrl}[Configure Maven to Build and Deploy the Quickstarts] to make sure you are configured correctly for testing the quickstarts.

== Use of {jbossHomeName}

In the following instructions, replace `__{jbossHomeName}__` with the actual path to your {productName} installation. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of {jbossHomeName} and JBOSS_HOME Variables].

== Configure the Server to Start With a Different Locale (Optional)

To start the {productName} server with a different locale than the system default:

. Make a backup copy of the `$ __{jbossHomeName}__/bin/standalone.conf` file.
. Edit the file and append commands to set the JVM parameters for the required country and language.
 The following example sets the country to Germany (`DE`) and the language to German (`de`).
+
[source,options="nowrap"]
----
JAVA_OPTS="$JAVA_OPTS -Duser.country=DE"
JAVA_OPTS="$JAVA_OPTS -Duser.language=de"
----
+
This can be done as a single line if you prefer:
+
[source,options="nowrap"]
----
JAVA_OPTS="$JAVA_OPTS -Duser.country=DE -Duser.language=de"
----

For more information about internationalization and localization, see http://www.oracle.com/technetwork/java/javase/tech/intl-139810.html.

== Start the Server

. Open a terminal and navigate to the root of the {productName} directory.
. Start the {productName} server with the default standalone profile by typing the following command.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:
+
[source,options="nowrap"]
----
$ mvn clean install wildfly:deploy
----

. This will deploy `target/{artifactId}.war` to the running instance of the server.

== Access the Application

The application will be running at the following URL: http://localhost:8080/{artifactId}/

This landing page provides details and links to test the quickstart features. You can also directly access the following URLs.

. `http://localhost:8080/{artifactId}/rest/greetings/__NAME__`

** Example: http://localhost:8080/{artifactId}/rest/greetings/Harold
** Demonstrates simple use of localized messages (with parameter) and logging.
** It returns the localized `hello __NAME__` string where `__NAME__` is the last component of the URL.
** It also logs the localized `Hello message sent` in the server log.
. `http://localhost:8080/{artifactId}/rest/greetings/__LOCALE__/__NAME__`

** Example: http://localhost:8080/{artifactId}/rest/greetings/fr-FR/Harold
** Demonstrates how to obtain a message bundle for a specified locale and how to throw a localized exceptions. Note that the localized exception is a wrapper around `WebApplicationException`.
** Returns a localized `hello __NAME__` string where `__NAME__` is the last component of the URL and the locale used is the one supplied in the `locale` URL.
** Logs a localized `Hello message sent in __LOCALE__` message using the JVM locale for the translation.
** If the supplied locale is invalid (in this case if it contains more than 3 components, eg. fr-FR-POSIX-FOO), it throws a `WebApplicationException` (404) using a localizable sub-class of `WebApplicationException`.
+
Note that `WebApplicationException` cannot be directly localized by JBoss Logging Tools using the `@Message` annotation due to the message parameter being ignored by the `WebApplicationException` constructors. Cases like this can be worked around by creating a subclass with a constructor that does deal with the message parameter.

. http://localhost:8080/{artifactId}/rest/greetings/crashme

** Demonstrates how to throw a localized exception with another exception specified as the cause. This is a completely contrived example.
** Attempts to divide by zero, catches the exception, and throws the localized one.
. `http://localhost:8080/{artifactId}/rest/dates/daysuntil/__TARGET_DATE__`

** Example: http://localhost:8080/{artifactId}/rest/dates/daysuntil/2020-12-25
** Demonstrates how to pass parameters through to the constructor of a localized exception, and how to specify an exception as a cause of a log message.
** Attempts to turn the `__TARGET_DATE__` URL component into a date object using the format `yyyy-MM-dd`
** Returns number of days (as an integer) until that date
** If the `__TARGET_DATE__` is invalid, for example, http://localhost:8080/{artifactId}/rest/dates/daysuntil/2015-02-31:
*** Catches the `ParseException`
*** Creates a localized `ParseException` passing values from the caught exception as parameters to its constructor
*** Logs a localized message with the localized exception as the cause
*** Throws a `WebApplicationException`(400) with the text from the localized `ParseException`

== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:
+
[source,options="nowrap"]
----
$ mvn wildfly:undeploy
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

You might see the following warning when you import this quickstart into JBoss Developer Studio. You can ignore this warning as it occurs in a generated file.

[source,options="nowrap"]
----
The import org.jboss.as.quickstarts.loggingToolsQS.exceptions.LocaleInvalidException is never used
GreeterExceptionBundle_$bundle.java
/{artifactId}/target/generated-sources/annotations/org/jboss/as/quickstarts/loggingToolsQS/exceptions  line 8
Java Problem
----

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

[source,options="nowrap"]
----
$ mvn dependency:sources
----
