apiVersion: wildfly.org/v1alpha1
kind: WildFlyServer
metadata:
  name: ejb-txn-remote-call-client
spec:
  env:
    - name: POSTGRESQL_DATABASE
      value: test
    - name: POSTGRESQL_JNDI
      value: "java:jboss/datasources/ejbJtaDs"
    - name: POSTGRESQL_PASSWORD
      value: test
    - name: POSTGRESQL_USER
      value: test
  applicationImage: "localhost:5000/ejb-txn-remote-call-client:latest"
  replicas: 1
