= xml-jaxp: Upload and Parse an XML File Using DOM or SAX
:author: Bartosz Baranowski
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: Intermediate
:technologies: JAXP, SAX, DOM, Servlet
:source: {githubRepoUrl}

[abstract]
The `xml-jaxp` quickstart demonstrates how to use Servlet and JSF to upload an XML file to {productName} and validate and parse it using DOM or SAX.

== What is it?

The `xml-jaxp` quickstart is a simple Java EE JAXP example that demonstrates how to use Servlet 3.0 and JSF to upload an XML file to _{productNameFull}_ and parse it using DOM or SAX, both of which are built into Java. It also shows how to use modules available in {productName}.

This quickstart provides an example XML schema and document file to use when testing this quickstart.

* The XML schema is located here: `__QUICKSTART_HOME__/src/main/resources/catalog.xsd`
* The XML document is located here: `__QUICKSTART_HOME__/src/main/resources/catalog.xml`

== System Requirements

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

All you need to build this project is {buildRequirements}. See link:{configureMavenDocUrl}[Configure Maven to Build and Deploy the Quickstarts] to make sure you are configured correctly for testing the quickstarts.

== Use of {jbossHomeName}

In the following instructions, replace `__{jbossHomeName}__` with the actual path to your {productName} installation. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of {jbossHomeName} and JBOSS_HOME Variables].

== Start the Server

. Open a terminal and navigate to the root of the {productName} directory.
. Start the {productName} server with the default standalone profile by typing the following command.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:
+
[source,options="nowrap"]
----
$ mvn clean install wildfly:deploy
----

. This will deploy `target/{artifactId}.war` to the running instance of the server.

== Access the Application

The application will be running at the following URL: http://localhost:8080/{artifactId}/.

To test the quickstart, follow these steps.

. Click the *Browse* button and navigate to the `__QUICKSTART_HOME__/src/main/resources/catalog.xml` file.
. Click the *Upload* button. The XML file content is parsed and displayed on the page.
. You should see the following output in the server console that shows the DOMXMLParser was used:
+
[source,options="nowrap"]
----
INFO  [stdout] (http-/127.0.0.1:8080-1) Parsing the document using the DOMXMLParser!
----

To enable the alternative SAXXMLParser parser:

. Remove the comments that surround the alternate parser element in the `WEB-INF/beans.xml` file.
. Redeploy the application using the instructions above and access the application in a browser at the following URL: http://localhost:8080/{artifactId}/.
. Click the *Browse* button and navigate to the `__QUICKSTART_HOME__/src/main/resources/catalog.xml` file.
. Click the *Upload* button. The XML file content is parsed and displayed on the page.
. You should now see following output in the server console:
+
[source,options="nowrap"]
----
INFO  [stdout] (http-/127.0.0.1:8080-1) Parsing the document using the SAXXMLParser!
----

== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:
+
[source,options="nowrap"]
----
$ mvn wildfly:undeploy
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

[source,options="nowrap"]
----
$ mvn dependency:sources
----
