= greeter: Demonstrates CDI, JPA, JTA, EJB, and JSF
:author: Pete Muir
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: Beginner
:technologies: CDI, JSF, JPA, EJB, JTA
:source: {githubRepoUrl}

[abstract]
The `greeter` quickstart demonstrates the use of CDI, JPA, JTA, EJB and JSF in {productName}.

== What is it?

The `greeter` quickstart demonstrates the use of CDI, JPA, JTA, EJB and JSF in {productNameFull}.

When you deploy this example, two users are automatically created for you: `emuster` and `jdoe`. This data is located in the `src/main/resources/import.sql file`.

To test this example:

. Enter a name in the *username* field and click on *Greet!*.
. If you enter a username that is not in the database, you get a message `No such user exists!`.
. If you enter a valid username, you get a message `Hello,` followed by the user's first and last name.
. To create a new user, click the *Add a new user* link. Enter the *username*, *first name*, and *last name*, and then click *Add User*. The user is added and a message displays the new user id number.
. Click on the `Greet a user!` link to return to the `Greet!` page.

//*************************************************
// Add notes about use in a production environment.
//*************************************************
:uses-h2:
:uses-ds-xml:
include::../development-shortcuts.adoc[leveloffset=+1]

== System Requirements

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

All you need to build this project is {buildRequirements}. See link:{configureMavenDocUrl}[Configure Maven to Build and Deploy the Quickstarts] to make sure you are configured correctly for testing the quickstarts.

== Use of {jbossHomeName}

In the following instructions, replace `__{jbossHomeName}__` with the actual path to your {productName} installation. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of {jbossHomeName} and JBOSS_HOME Variables].

== Start the Server

. Open a terminal and navigate to the root of the {productName} directory.
. Start the {productName} server with the default standalone profile by typing the following command.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:
+
----
$ mvn clean install wildfly:deploy
----

. This will deploy `target/{artifactId}.war` to the running instance of the server.

== Access the Application

The application will be running at the following URL: http://localhost:8080/{artifactId}/.

== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:
+
----
$ mvn wildfly:undeploy
----

== Server Log: Expected Warnings and Errors

You will see the following warnings in the server log. You can ignore these warnings.
----
WFLYJCA0091: -ds.xml file deployments are deprecated. Support may be removed in a future version.

HHH000431: Unable to determine H2 database version, certain features may not work
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

----
$ mvn dependency:sources
----
