---
apiVersion: v1
kind: Service
metadata:
  name: microprofile-health-management
  labels:
    app.kubernetes.io/instance: microprofile-health
    app.kubernetes.io/name: microprofile-health
spec:
  ports:
    - name: management
      protocol: TCP
      port: 9990
      targetPort: 9990
  selector:
    app.kubernetes.io/instance: microprofile-health
    app.kubernetes.io/name: microprofile-health
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: microprofile-health-management
  labels:
    app.kubernetes.io/name: microprofile-health
spec:
  port:
    targetPort: management
  to:
    kind: Service
    name: microprofile-health-management
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

