= servlet-filterlistener: How to Write Servlet Filters and Listeners
:author: Jonathan Fuerth
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../shared-doc/attributes.adoc[]

:level: Intermediate
:technologies: Servlet Filter, Servlet Listener
:source: {githubRepoUrl}

[abstract]
The `servlet-filterlistener` quickstart demonstrates how to use Servlet filters and listeners in an application.

== What is it?

The `servlet-filterlistener` quickstart demonstrates how to use Servlet filters and listeners in {productNameFull}.

This example contains the following classes:

* `FilterExampleServlet`: A simple servlet that prints a form that contains an input field and a _Send_ button.
* `VowelRemoverFilter`: A servlet filter that removes the vowels from the text entered in the form.
* `ParameterDumpingRequestListener`: A simple servlet request listener that creates a map of the original HTTP request parameter values before the filter is applied.

//*************************************************
// Add System Requirements
//*************************************************
// == System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]

//*************************************************
// Add Use of JBoss Home Name
//*************************************************
// == Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]

//*************************************************
// Start the server with the default profile
//*************************************************
// == Start the Server with the Default Profile
include::../shared-doc/start-server-default-profile.adoc[leveloffset=+1]

== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:
+
[source,options="nowrap"]
----
$ mvn clean install wildfly:deploy
----

. This will deploy `target/{artifactId}.war` to the running instance of the server.

== Access the Application

The application will be running at the following URL http://localhost:8080/{artifactId}/.

You are presented with a form containing an input field and a _Send_ button. To test the quickstart:

. Enter some text in the field, for example:
+
[source,options="nowrap"]
----
This is only a test!
----

. Click _Send_.
. The servlet filter intercepts and removes the vowels from the text entered in the form and displays:
+
[source,options="nowrap"]
----
You Typed: Ths s nly tst!
----

. The server console displays the following log messages.
+
The following messages appear in the log when you access the application URL. This is because the ParameterDumpingRequestListener, which is a ServletRequestListener, and the VowelRemoverFilter both map to the application context and print logs for every request. Note that the VowelRemoveFilter contains logic to handle empty input field arguments.
+
[source,options="nowrap"]
----
INFO  [io.undertow.servlet] (default task-46) ParameterDumpingRequestListener: request has been initialized. It has 0 parameters:
INFO  [io.undertow.servlet] (default task-46) VowelRemoverFilter initialized
INFO  [io.undertow.servlet] (default task-46) VowelRemoverFilter invoking filter chain...
INFO  [io.undertow.servlet] (default task-46) VowelRemoverFilter done filtering request
INFO  [io.undertow.servlet] (default task-46) ParameterDumpingRequestListener: request has been destroyed
INFO  [io.undertow.servlet] (default task-48) ParameterDumpingRequestListener: request has been initialized. It has 0 parameters:
INFO  [io.undertow.servlet] (default task-48) VowelRemoverFilter invoking filter chain...
INFO  [io.undertow.servlet] (default task-48) VowelRemoverFilter done filtering request
INFO  [io.undertow.servlet] (default task-48) ParameterDumpingRequestListener: request has been destroyed
----
+
The following messages appear in the log when you type "This is only a test!" in the input field and click `Send`.
+
[source,options="nowrap"]
----
INFO  [io.undertow.servlet] (default task-50) ParameterDumpingRequestListener: request has been initialized. It has 1 parameters:
INFO  [io.undertow.servlet] (default task-50)   userInput=This is only a test!
INFO  [io.undertow.servlet] (default task-50) VowelRemoverFilter invoking filter chain...
INFO  [io.undertow.servlet] (default task-50) VowelRemoverFilter done filtering request
INFO  [io.undertow.servlet] (default task-50) ParameterDumpingRequestListener: request has been destroyed
----

== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:
+
[source,options="nowrap"]
----
$ mvn wildfly:undeploy
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

[source,options="nowrap"]
----
$ mvn dependency:sources
----
