Introduction
============
:Author: Pete Muir

This guide will walk you through installing and starting up JBoss WildFly. It will then introduce key features of the Jakarta EE (Web Profile) programming model, of which JBoss WildFly is a certified implementation.


[TIP]
.Jakarta EE
========================================================================
The Jakarta EE platform offers developers the ability to write
distributed, transactional and portable applications quickly and easily.
We class applications that require these capabilities "enterprise
applications". These applications must be fast, secure and reliable.

Jakarta EE has always offered strong messaging (JMS), transactional (JTA)
and resource (JCA) capabilities as well as exposing web services via
SOAP (JAX-WS).
========================================================================


JBoss WildFly depart from the familiar structure of previous JBoss AS versions, so we recommend all developers follow the steps in https://github.com/wildfly/quickstart/blob/10.x/guide/GettingStarted.asciidoc[Getting Started with JBoss WildFly] to install and start up the application server for the first time.

JBoss WildFly come with a series of quickstarts aimed to get you up to writing applications with minimal fuss. We recommend to start by working through the quickstarts in this guide, in the order they are presented. If you have previous experience with Jakarta EE 6, you may wish to skip some or all of the quickstarts.

*Core*

. https://github.com/wildfly/quickstart/blob/10.x/guide/HelloworldQuickstart.asciidoc[Helloworld Quickstart]. If you have previously developed applications using technologies such as JSF or Wicket, and EJB or Spring, you may wish to skip this quickstart.
. https://github.com/wildfly/quickstart/blob/10.x/guide/NumberguessQuickstart.asciidoc[Numberguess Quickstart]. If you have previously developed applications using technologies such as JSF or Wicket, EJB or Spring, and JPA or Hibernate you may wish to skip this quickstart.
. https://github.com/wildfly/quickstart/blob/10.x/guide/GreeterQuickstart.asciidoc[Greeter Quickstart]. If you are a Jakarta EE wizard you may wish to skip this quickstart.
. https://github.com/wildfly/quickstart/blob/10.x/guide/KitchensinkQuickstart.asciidoc[Kitchensink Quickstart]. A great starting point for your project.


Downloading the quickstarts
---------------------------

The quickstarts are are available for download from link:https://github.com/wildfly/quickstart[JBoss Developer Framework]. Make sure you download the latest zip!
