Introduction
============
:Author: Pete Muir

This guide will walk you through installing and starting up JBoss Enterprise Application Platform 6 or JBoss AS 7. It will then introduce key features of the Java EE 6 (Web Profile) programming model, of which JBoss AS 7 is a certified implementation.


[TIP]
.Java EE 6
========================================================================
The Java EE 6 platform offers developers the ability to write 
distributed, transactional and portable applications quickly and easily. 
We class applications that require these capabilities "enterprise 
applications". These applications must be fast, secure and reliable.

Java EE has always offered strong messaging (JMS), transactional (JTA) 
and resource (JCA) capabilities as well as exposing web services via 
SOAP (JAX-WS). Java EE 5 started a radical shift for the programming 
model, offering a powerful, declarative and lightweight 
object-relational mapper (JPA) and  annotation-driven, lightweight 
access to enterprise services (EJB 3). Java EE 6 added a type-safe, 
loosely coupled programming model (CDI), declarative validation of 
constraints (Bean Validation) and RESTful web services (JAX-RS) to 
produce a complete, modern development environment.
========================================================================


JBoss Enterprise Application Platform 6 and JBoss AS 7 depart from the familiar structure of previous JBoss AS versions, so we recommend all developers follow the steps in <<GettingStarted-, Getting Started with JBoss Enterprise Application Platform 6 or JBoss AS 7>> to install and start up the application server for the first time. 

JBoss Enterprise Application Platform 6 and JBoss AS 7 come with a series of quickstarts aimed to get you up to writing applications with minimal fuss. We recommend that start by working through the quickstarts in this guide, in the order they are presented. If you have previous experience with Java EE 6, you may wish to skip some or all of the quickstarts.

*Core*

. <<HelloworldQuickstart-, Helloworld Quickstart>>. If you have previously developed applications using technologies such as JSF or Wicket, and EJB or Spring, you may wish to skip this quickstart.
. <<NumberguessQuickstart-, Numberguess Quickstart>>. If you have previously developed applications using technologies such as JSF or Wicket, EJB or Spring, and JPA or Hibernate you may wish to skip this quickstart.
. <<GreeterQuickstart-, Greeter Quickstart>>. If you are a Java EE wizard you may wish to skip this quickstart.
. <<KitchensinkQuickstart-, Kitchensink Quickstart>>. A great starting point for your project.

*Optional*
[start=5]
. <<HelloworldOSGiQuickstart-, OSGi Helloworld Quickstart>>. If you want to get started with OSGi, check out this quickstart.

Downloading the quickstarts
---------------------------

The quickstarts are are available for download from link:http://www.jboss.org/jdf/quickstarts/get-started[JBoss Developer Framework]. Make sure you download the latest zip! 

