= jaxws-addressing: A WS-addressing JAX-WS Web Service
:author: R Searls
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../shared-doc/attributes.adoc[]

:level: Beginner
:technologies: JAX-WS
:source: {githubRepoUrl}

[abstract]
The `jaxws-addressing` quickstart is a working example of the web service using WS-Addressing.

== What is it?

The `jaxws-addressing` quickstart demonstrates the use of _JAX-WS_ in {productNameFull} as a simple WS-addressing application.

//*************************************************
// Add System Requirements
//*************************************************
// == System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]

//*************************************************
// Add Use of JBoss Home Name
//*************************************************
// == Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]

//*************************************************
// Start the server with the default profile
//*************************************************
// == Start the Server with the Default Profile
include::../shared-doc/start-server-default-profile.adoc[leveloffset=+1]

[[install_the_quickstart_parent_artifact_in_maven]]
== Install the Quickstart Parent Artifact in Maven

This quickstart requires the `quickstart-parent` artifact to be installed in your local Maven repository. To install it, navigate to your __QUICKSTART_HOME__ directory  directory and run the following command.

[source,subs="+quotes,attributes+",options="nowrap"]
----
$ cd __QUICKSTART_HOME__
$ mvn clean install
----

== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:
+
[source,options="nowrap"]
----
$ mvn clean install wildfly:deploy
----

. This will create the `{artifactId}-client.jar` and deploy `service/target/{artifactId}-service.war` to the running instance of the server.

== Access the Application

You can check that the Web Service is running and deployed correctly by accessing the following URL: http://localhost:8080/{artifactId}/AddressingService?wsdl. This URL will display the deployed WSDL endpoint for the Web Service.

== Run the Client

. Make sure you xref:install_the_quickstart_parent_artifact_in_maven[Install the Quickstart Parent Artifact in Maven].

. Verify that the service is deployed properly.

. Open a terminal and navigate into the client directory of this quickstart.
+
[source,options="nowrap"]
----
$ cd client/
----

. Type this command to run the client.
+
[source,options="nowrap"]
----
$ mvn exec:java
----

. You should see the following output in the client console.
+
[source,options="nowrap"]
----
Hello World!
----

== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:
+
[source,options="nowrap"]
----
$ mvn wildfly:undeploy
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

For this quickstart, follow the special instructions to link:{useEclipseDeployJavaClientDocUrl}[Deploy and Undeploy a Quickstart Containing Server and Java Client Projects]

. To build all of the artifacts, right-click on the *{artifactId}* parent project, and choose *Run As* –> *Maven install*.
. To deploy the service:
** Right-click on the *{artifactId}-service* subproject, and choose *Run As* –> *Run on Server*.
** Choose the server and click *Finish*.
** This starts the server and deploys the service to the server.
** You also see the "404 - Not Found" error in the application window. This is because there is no user interface for this quickstart. You can ignore this error.
. To access the application:
** Right-click on the *{artifactId}-client* subproject and choose *Run As* –> *Java Application*.
** You should see the following message in the *Console* tab:
+
[source,options="nowrap"]
----
Hello World!
----

. To undeploy the project, right-click on the *{artifactId}* parent project and choose *Run As* –> *Maven build*. Enter `wildfly:undeploy` for the *Goals* and click *Run*.

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

[source,options="nowrap"]
----
$ mvn dependency:sources
----
