= resteasy-jaxrs-client: External JAX-RS Client
:author: Blaine Mincey
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: Intermediate
:technologies: JAX-RS, CDI
:source: {githubRepoUrl}
:prerequisites: helloworld-rs

[abstract]
The `resteasy-jaxrs-client` quickstart demonstrates an external JAX-RS RestEasy client, which interacts with a JAX-RS Web service that uses *CDI* and *JAX-RS*.

== What is it?

The `resteasy-jaxrs-client` quickstart demonstrates an external JAX-RS RestEasy client which interacts with a JAX-RS Web service that uses _CDI_ and _JAX-RS_
in {productNameFull}.

This client "calls" the HelloWorld JAX-RS Web Service that was created in the link:../helloworld-rs/README.md[helloworld-rs] quickstart. See the *Prerequisite* section below for details on how to build and deploy the link:../helloworld-rs/README.md[helloworld-rs] quickstart.

== System Requirements

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

All you need to build this project is {buildRequirements}. See https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONFIGURE_MAVEN_JBOSS_EAP7.md#configure-maven-to-build-and-deploy-the-quickstarts[Configure Maven for {productName} {productVersion}] to make sure you are configured correctly for testing the quickstarts.

== Prerequisites

IMPORTANT: This quickstart depends on the deployment of the `helloworld-rs` quickstart for its test. Before running this quickstart, see the link:../helloworld-rs/README.md[helloworld-rs] README file for details on how to deploy it.

You can verify the deployment of the link:../helloworld-rs/README.md[helloworld-rs] quickstart by accessing the following content:

* The _XML_ content can be viewed by accessing the following URL: http://localhost:8080/helloworld-rs/rest/xml
* The _JSON_ content can be viewed by accessing this URL: http://localhost:8080/helloworld-rs/rest/json

== Run the Client

. Make sure you have started the {productName} server as described above.
. Make sure the `helloworld-rs` quickstart has been deployed on the server as noted in the *Prerequisites* section above.
. Open a command prompt and navigate to the root directory of this quickstart.
. Type the following command to run the client:

----
mvn clean package exec:java
----

== Investigate the Console Output

This command will compile the example and execute a test to make two separate requests to the Web Service. Towards the end of the Maven build output, you
should see the following if the execution is successful:

----
    ===============================================
    URL: http://localhost:8080/helloworld-rs/rest/xml
    MediaType: application/xml

    *** Response from Server ***

    <xml><result>Hello World!</result></xml>

    ===============================================
    ===============================================
    URL: http://localhost:8080/helloworld-rs/rest/json
    MediaType: application/json

    *** Response from Server ***

    {"result":"Hello World!"}
    ===============================================
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

. Before you run this quickstart, be sure to import, deploy, and test the `helloworld-rs` quickstart as described in the <<prerequisites,Prerequisites>> section of this file.

. Import this quickstart into JBoss Developer Studio.

. Build and run the quickstart project.

** Right-click on the `{artifactId}` project and choose `Run As` –&gt; `Maven build`.
** Enter `clean package exec:java` for the `Goals:` and click `Run`.
** The client output displays in the `Console` window.
. To undeploy the `helloworld-rs` quickstart, right-click on the `helloworld-rs` project and choose `Run As` –&gt; `Maven build`. Enter `wildfly:undeploy` for the `Goals` and click `Run`.