= payment-cdi-event: Use CDI Events to Process Debit and Credit Operations
:author: Elvadas Nono
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: Beginner
:technologies: CDI, JSF
:source: {githubRepoUrl}

[abstract]
The `payment-cdi-event` quickstart demonstrates how to create credit and debit CDI Events in {productName}, using a JSF front-end client.

== What is it?

The `payment-cdi-event` quickstart demonstrates how to use CDI Events in {productNameFull}.

The JSF front-end client allows you to create both credit and debit operation events.

To test this quickstart, enter an amount, choose either a Credit or Debit operation, and then click on _Pay_ to create the event.

A Session scoped (`@SessionScoped`) payment event handler catches the operation and produces (`@Produces`) a named list of all operations performed during this session. The event is logged in the {productName} server log and the event list is displayed in a table at the bottom of the form.

The `payment-cdi-event` quickstart defines the following classes and interfaces:

* The `beans` package contains the `PaymentBean` bean class:
* This is a session scoped bean that stores the payment form information:
** payment amount
** operation type: debit or credit
* It contains the following utility methods:
** `private void init()`: This is a PostConstruct (`@PostConstruct`) method that performs initialization before the class is put into service. It resets the `amount` to `$0` and the `paymentOption` to the default type of debit.
** `public String pay()`: This method processes the operation when the user clicks on submit. We have only one JSF page, so the method does not return anything and the flow of control does not change.
** `public void reset()`: Reset calls the `init()` method reinitialize the form values.
* The `events` package contains the `PaymentEvent` class and the enum `PaymentTypeEnum`.
* `PaymentEvent`: We have only one event that handles both credit and debit operations. Qualifiers help us to make the difference at injection point.
* `PaymentTypeEnum`: A typesafe enum is used to represent the operation payment type. It contains utility methods to convert between `String` and `Enum`.
* The `qualifiers` package contains the `Credit` and `Debit` interfaces. The annotation determines the operation of the injecting `Event`.
* The `handler` package contains interfaces and implementations of `PaymentEvent` observers.
* `ICreditEventObserver`: Interface to listen to `CREDIT` event only (`@Observes` `@Credit`).
* `IDebitEventObserver`: Interface to listen to `DEBIT` event (`@Observes` `@Debit`).
* `PaymentHandler`: The concrete implementation of the payment handler.
** It implements both `ICreditEventObserver` and `IDebitEventObserver`.
** The payment handler exposes the list of events caught during a session (`@Named` `name=payments`).
* The `resources` package contains the `Resources` class that produces the logger for the application.

== System Requirements

The application this project produces is designed to be run on {productNameFull} {productVersion} or later.

All you need to build this project is {buildRequirements}. See link:{configureMavenDocUrl}[Configure Maven to Build and Deploy the Quickstarts] to make sure you are configured correctly for testing the quickstarts.

== Use of {jbossHomeName}

In the following instructions, replace `__{jbossHomeName}__` with the actual path to your {productName} installation. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of {jbossHomeName} and JBOSS_HOME Variables].

== Start the {productName} Server

. Open a terminal and navigate to the root of the {productName} directory.
. Start the {productName} server with the default standalone profile by typing the following command.
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:
+
[source,options="nowrap"]
----
$ mvn clean install wildfly:deploy
----

. This will deploy `target/{artifactId}.war` to the running instance of the server.

== Access the Application

The application will be running at the following URL: http://localhost:8080/{artifactId}/.

== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:
+
[source,options="nowrap"]
----
$ mvn wildfly:undeploy
----

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

[source,options="nowrap"]
----
$ mvn dependency:sources
----
