include::../shared-doc/attributes.adoc[]

= payment-cdi-event: Use CDI Events to Process Debit and Credit Operations
:author: Elvadas Nono
:level: Beginner
:technologies: CDI, JSF

[abstract]
The `payment-cdi-event` quickstart demonstrates how to create credit and debit CDI Events in {productName}, using a JSF front-end client.

:standalone-server-type: default
:archiveType: war

//*************************************************
// Shared CD and Product Release content
//*************************************************

== What is it?

The `payment-cdi-event` quickstart demonstrates how to use CDI Events in {productNameFull}.

The JSF front-end client allows you to create both credit and debit operation events.

To test this quickstart, enter an amount, choose either a Credit or Debit operation, and then click on _Pay_ to create the event.

A Session scoped (`@SessionScoped`) payment event handler catches the operation and produces (`@Produces`) a named list of all operations performed during this session. The event is logged in the {productName} server log and the event list is displayed in a table at the bottom of the form.

The `payment-cdi-event` quickstart defines the following classes and interfaces:

* The `beans` package contains the `PaymentBean` bean class:
* This is a session scoped bean that stores the payment form information:
** payment amount
** operation type: debit or credit
* It contains the following utility methods:
** `private void init()`: This is a PostConstruct (`@PostConstruct`) method that performs initialization before the class is put into service. It resets the `amount` to `$0` and the `paymentOption` to the default type of debit.
** `public String pay()`: This method processes the operation when the user clicks on submit. We have only one JSF page, so the method does not return anything and the flow of control does not change.
** `public void reset()`: Reset calls the `init()` method reinitialize the form values.
* The `events` package contains the `PaymentEvent` class and the enum `PaymentTypeEnum`.
* `PaymentEvent`: We have only one event that handles both credit and debit operations. Qualifiers help us to make the difference at injection point.
* `PaymentTypeEnum`: A typesafe enum is used to represent the operation payment type. It contains utility methods to convert between `String` and `Enum`.
* The `qualifiers` package contains the `Credit` and `Debit` interfaces. The annotation determines the operation of the injecting `Event`.
* The `handler` package contains interfaces and implementations of `PaymentEvent` observers.
* `ICreditEventObserver`: Interface to listen to `CREDIT` event only (`@Observes` `@Credit`).
* `IDebitEventObserver`: Interface to listen to `DEBIT` event (`@Observes` `@Debit`).
* `PaymentHandler`: The concrete implementation of the payment handler.
** It implements both `ICreditEventObserver` and `IDebitEventObserver`.
** The payment handler exposes the list of events caught during a session (`@Named` `name=payments`).
* The `resources` package contains the `Resources` class that produces the logger for the application.


//*************************************************
// Product Release content only
//*************************************************

ifndef::EAPCDRelease[]

// System Requirements
include::../shared-doc/system-requirements.adoc[leveloffset=+1]
// Use of {jbossHomeName}
include::../shared-doc/use-of-jboss-home-name.adoc[leveloffset=+1]
// Start the {productName} Standalone Server
include::../shared-doc/start-the-standalone-server.adoc[leveloffset=+1]
// Build and Deploy the Quickstart
include::../shared-doc/build-and-deploy-the-quickstart.adoc[leveloffset=+1]

== Access the Application

The application will be running at the following URL: http://localhost:8080/{artifactId}/.

// Undeploy the Quickstart
include::../shared-doc/undeploy-the-quickstart.adoc[leveloffset=+1]
// Run the Quickstart in Red Hat CodeReady Studio or Eclipse
include::../shared-doc/run-the-quickstart-in-jboss-developer-studio.adoc[leveloffset=+1]
// Debug the Application
include::../shared-doc/debug-the-application.adoc[leveloffset=+1]

endif::[]

//*************************************************
// CD Release content only
//*************************************************

ifdef::EAPCDRelease[]

// Getting Started with OpenShift
include::../shared-doc/cd-openshift-getting-started.adoc[leveloffset=+1]
//Prepare OpenShift for Quickstart Deployment
include::../shared-doc/cd-create-project.adoc[leveloffset=+1]
// Import the Latest {xpaasproduct-shortname} Image Streams and Templates
include::../shared-doc/cd-import-imagestreams-templates.adoc[leveloffset=+1]
// Deploy the {ProductShortName} Source-to-Image (S2I) Quickstart to OpenShift
include::../shared-doc/cd-deploy-project.adoc[leveloffset=+1]
// OpenShift Post Deployment Tasks: This is not currently needed.
// include::../shared-doc/cd-post-deployment-tasks.adoc[leveloffset=+1]

endif::[]
