= ejb-security-jaas: Using the legacy JAAS security domains to secure JEE applications
:author: Stefan Guilhen
:productName: WildFly
:productNameFull: WildFly Application Server
:jbossHomeName: WILDFLY_HOME
:productVersion: 12
:buildRequirements: Java 8.0 (Java SDK 1.8) or later and Maven 3.3.1 or later
include::../attributes.adoc[]

:level: Intermediate
:technologies: EJB, Security
:source: {githubRepoUrl}

[abstract]
The `ejb-security-jaas` quickstart demonstrates how legacy `JAAS` security domains can be used in conjunction with `Elytron`

Source: &lt;{githubRepoUrl}&gt;

== What is it?

The `ejb-security-jaas` quickstart demonstrates how legacy `JAAS`-based security domains can be used in conjunction with `WildFly Elytron` to secure JEE applications. The secured EJB component can be accessed indirectly using a web application and it can also be directly invoked by a remote client. This quickstart shows how {productNameFull} must be configured to support both scenarios using the legacy `JAAS` integration.

The overall steps required to use the `JAAS` integration are as follows:
1. Specify a `JAAS` security domain in the legacy `security` subsystem.
2. Export an `Elytron`-compatible security realm that delegates to the legacy JAAS security domain.
3. Create a `security-domain` in the `elytron` subsystem that uses the exported realm.
4. Setup an `http-authentication-factory` in the `elytron` subsystem to handle the web requests.
5. Setup a `sasl-authentication-factory` in the `elytron` subsystem to handle the requests made by remote clients.
6. Add the `application-security-domain` mappings to both `ejb3` and `undertow` subsystems to enable `Elytron` security for the EJB3 and web components.

== System Requirements

The applications these projects produce are designed to be run on {productNameFull} {productVersion} or later.

All you need to build these projects is {buildRequirements}. See link:{configureMavenDocUrl}[Configure Maven to Build and Deploy the Quickstarts] to make sure you are configured correctly for testing the quickstarts.

To run these quickstarts with the provided build scripts, you need the {productName} distribution ZIP. For information on how to install and run JBoss, see the https://access.redhat.com/documentation/en/red-hat-jboss-enterprise-application-platform/[{productNameFull} Documentation] _Getting Started Guide_ located on the Customer Portal.

You can also use <<use_jboss_developer_studio_or_eclipse_to-run_the_quickstarts,JBoss Developer Studio or Eclipse>> to run the quickstarts.

== Use of {jbossHomeName}

In the following instructions, replace `__{jbossHomeName}__` with the actual path to your {productName} installation. The installation path is described in detail here: link:{useProductHomeDocUrl}[Use of {jbossHomeName} and JBOSS_HOME Variables].

== Create the Properties Files for the JAAS Security Domain

. Open a command line and navigate to the {productName} server `configuration` directory:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ cd __{jbossHomeName}__/standalone/configuration/
----

. Create a file named `users.properties` and add the following username/password pair:
+
----
quickstartUser=quickstartPwd1!
----

. Create a file named `roles.properties` and add the following username/roles pair:
+
----
quickstartUser=guest
----

== Configure the Server

These steps assume you are running the server in standalone mode and using the default `standalone.xml` supplied with the distribution.

You configure the security domain by running JBoss CLI commands. For your convenience, this quickstart batches the commands into a `configure-elytron-jaas.cli` script provided in the root directory of this quickstart.

. Before you begin, back up your server configuration file

** If it is running, stop the {productName} server.
** Back up the file: `__{jbossHomeName}__/standalone/configuration/standalone.xml`
** After you have completed testing this quickstart, you can replace this file to restore the server to its original configuration.
. Start the {productName} server by typing the following:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

. Review the `configure-elytron-jaas.cli` file in the root of this quickstart directory. This script adds the configuration that enables Elytron security for the quickstart components. Comments in the script describe the purpose of each block of commands.
. Open a new terminal, navigate to the root directory of this quickstart, and run the following command, replacing __{jbossHomeName}__ with the path to your server:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=configure-elytron-jaas.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

. Stop the {productName} server.

== Review the Modified Server Configuration

After stopping the server, open the `__{jbossHomeName}__/standalone/configuration/standalone.xml` file and review the changes.

. The following `security-domain` was added to the legacy `security` subsystem:
+
[source,xml,options="nowrap"]
----
<security-domain name="quickstart-domain" cache-type="default">
    <authentication>
        <login-module code="Remoting" flag="optional">
            <module-option name="password-stacking" value="useFirstPass"/>
        </login-module>
        <login-module code="UsersRoles" flag="required">
            <module-option name="usersProperties" value="${jboss.server.config.dir}/users.properties"/>
            <module-option name="rolesProperties" value="${jboss.server.config.dir}/roles.properties"/>
            <module-option name="password-stacking" value="useFirstPass"/>
        </login-module>
    </authentication>
    <mapping>
        <mapping-module code="SimpleRoles" type="role">
            <module-option name="quickstartUser" value="admin"/>
        </mapping-module>
    </mapping>
</security-domain>
----

. The following `elytron-realm` was added to the legacy `security` subsystem:
+
[source,xml,options="nowrap"]
----
<elytron-integration>
    <security-realms>
        <elytron-realm name="LegacyRealm" legacy-jaas-config="quickstart-domain" apply-role-mappers="false"/>
    </security-realms>
</elytron-integration>
----

. The following `security-domain` was added to the `elytron` subsystem:
+
[source,xml,options="nowrap"]
----
<security-domain name="LegacyDomain" default-realm="LegacyRealm" permission-mapper="default-permission-mapper" security-event-listener="local-audit">
    <realm name="LegacyRealm"/>
</security-domain>
----

. The following `http-authentication-factory` was added to the `elytron` subsystem:

+
[source,xml,options="nowrap"]
----
<http-authentication-factory name="quickstart-http-authentication" http-server-mechanism-factory="global" security-domain="LegacyDomain">
    <mechanism-configuration>
        <mechanism mechanism-name="BASIC">
            <mechanism-realm realm-name="Legacy Realm"/>
        </mechanism>
    </mechanism-configuration>
</http-authentication-factory>
----

. The following `application-security-domain` mapping was added to the `undertow` subsystem:
+
[source,xml,otions="nowrap"]
----
<application-security-domains>
    <application-security-domain name="legacy-domain" http-authentication-factory="quickstart-http-authentication"/>
</application-security-domains>
----

. The following `sasl-authentication-factory` was added to the `elytron` subsystem:

+
[source,xml,options="nowrap"]
----
<sasl-authentication-factory name="quickstart-sasl-authentication" sasl-server-factory="configured" security-domain="LegacyDomain">
    <mechanism-configuration>
        <mechanism mechanism-name="PLAIN"/>
    </mechanism-configuration>
</sasl-authentication-factory>
----

. The `http-remoting-connector` in the `remoting` subsystem was updated to use the `sasl-authentication-factory` created in step 6:

+
[source,xml,options="nowrap"]
----
<http-connector name="http-remoting-connector" connector-ref="default" security-realm="ApplicationRealm" sasl-authentication-factory="quickstart-sasl-authentication"/>
----

. Finally, the following `application-security-domain` mapping was added to the `ejb3` subsystem:

+
[source,xml,options="nowrap"]
----
<application-security-domains>
    <application-security-domain name="legacy-domain" security-domain="LegacyDomain"/>
</application-security-domains>
----

== Start the Server

. Open a terminal and navigate to the root of the {productName} directory.
. The following shows the command line to start the server:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

== Build and Deploy the Quickstart

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. Type this command to build and deploy the archive:
+
----
$ mvn clean install wildfly:deploy
----

. This will deploy `target/{artifactId}.war` to the running instance of the server.

== Access the Application

The application will be running at the following URL http://localhost:8080/{artifactId}/.

When you access the application, you are presented with a browser login challenge.

. If you attempt to login with a user name and password combination that has not been added to the server, the login challenge will be redisplayed.
. When you login successfully using `quickstartUser`/`quickstartPwd1!`, the browser displays the following security info:
+
----
Successfully called Secured EJB

Principal : quickstartUser
Remote User : quickstartUser
Has admin permission : false
Authentication Type : BASIC
----

. The application can also be accessed directly by a remote client. Type the following command in the root directory of the quickstart:
+
----
$ mvn exec:exec
----

. Next, change the exported realm so that it now uses the legacy role mappers as defined in the legacy `JAAS` security domain.
+
Make sure you are still in the root directory of this quickstart, and run the following command, replacing `__{jbossHomeName}__`
with the path to your server:

. If you didn't close your web browser, re-load the quickstart application page. Otherwise open a new browser, point it to the
URL http://localhost:8080/{artifactId}/ and login with `quickstartUser/quickstartPwd1!`. It should now display a
page confirming the user now has the `admin` role that was provided by the legacy role mapper:
+
----
Successfully called Secured EJB

Principal : quickstartUser
Remote User : quickstartUser
Has admin permission : true
Authentication Type : BASIC
----

. The same result can be observed when re-running the remote client application:
+
----
    * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

    Called secured bean, caller principal quickstartUser

    Principal has admin permission: true

    * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
----

== Undeploy the Archive

. Make sure you have started the {productName} server as described above.
. Open a terminal and navigate to the root directory of this quickstart.
. When you are finished testing, type this command to undeploy the archive:
+
----
$ mvn wildfly:undeploy
----

== Restore the Server Configuration

You can restore the original server configuration by running the `restore-configuration.cli` script provided in the root directory of this quickstart or by manually restoring the backup copy the configuration file.

=== Restore the Server Configuration by Running the JBoss CLI Script

. Start the {productName} server by typing the following:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/standalone.sh
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\standalone.bat` script.

. Open a new terminal, navigate to the root directory of this quickstart, and run the following command, replacing __{jbossHomeName}__ with the path to your server:
+
[source,subs="+quotes,attributes+",options="nowrap"]
----
$ __{jbossHomeName}__/bin/jboss-cli.sh --connect --file=restore-configuration.cli
----
+
NOTE: For Windows, use the `__{jbossHomeName}__\bin\jboss-cli.bat` script.

=== Restore the Server Configuration Manually

. If it is running, stop the {productName} server.
. Replace the `__{jbossHomeName}__/standalone/configuration/standalone.xml` file with the backup copy of the file.

== Remove the Properties Files from the Server

After you are done with this quickstart, remember to remove the `users.properties` and `roles.properties` files from the
server configuration directory (`__{jbossHomeName}__/standalone/configuration/`).

== Run the Quickstart in Red Hat JBoss Developer Studio or Eclipse

You can also start the server and deploy the quickstarts or run the Arquillian tests from Eclipse using JBoss tools. For general information about how to import a quickstart, add a {productName} server, and build and deploy a quickstart, see link:{useEclipseUrl}[Use JBoss Developer Studio or Eclipse to Run the Quickstarts].

* Be sure to <<create_the_properties_files_for_the_jaas_security_domain,Create the Properties Files for the JAAS Security Domain>> as described above.
* Be sure to configure the server by running the JBoss CLI script as described above under <<configure-the-server,Configure the Server>>. Stop the server at the end of that step.
* To deploy the application to the {productName} server, right-click on the *{artifactId}* project and choose *Run As* -> *Run on Server*.
* You are presented with a browser login challenge. Enter the credentials as described above under <<access_the_application,Access the Application>> to see the running application. Note that *Has admin permission* is `false`.
* Leave the application running in JBoss Developer Studio. To configure the server to use the legacy role mappers, open a terminal, and run the `enable-role-mappers.cli` script as described above under <<access_the_application,Access the Application>>.
* Go back to JBoss Developer Studio and click *Refresh the current page*. Note that *Has admin permission* is now `true`.
* To undeploy the project, right-click on the *{artifactId}* project and choose *Run As* -> *Maven build*. Enter `wildfly:undeploy` for the *Goals* and click *Run*.
* Be sure to <<restore_the_server_configuration,Restore the Server Configuration>> when you have completed testing this quickstart.

== Debug the Application

If you want to debug the source code of any library in the project, run the following command to pull the source into your local repository. The IDE should then detect it.

----
$ mvn dependency:sources
----
