=== Install AMQ Streams on OpenShift

The functionality of this quickstart depends on a running instance of the
https://access.redhat.com/products/red-hat-amq#streams[AMQ Streams] Operator. AMQ Streams is a Red Hat project based on Apache Kafka. To deploy AMQ Streams in the Openshift environment:

WARNING: For simplicity, this quickstart installs the AMQ Streams operator globally in the `openshift-operators` namespace, making it available across all namespaces in the cluster. The `openshift-operators` namespace already contains a `global-operators` OperatorGroup, so you must NOT create an additional OperatorGroup or the operator will fail to start. In production environments, consider namespace-scoped installation (see note below) to limit scope and improve security.

. Log in into the Openshift console as `kubeadmin` user (or any cluster administrator).
. Install the `Streams for Apache Kafka` operator globally.

In your terminal, run the following command to subscribe the `Streams for Apache Kafka` operator.
[options="nowrap",subs="+attributes"]
----
$ oc apply -f ./charts/amq-operator-on-openshift.yaml --wait --timeout=10m0s
----

NOTE: For namespace-scoped installation: Edit `charts/amq-operator-group-on-openshift.yaml` to replace `<your-namespace>` with your project namespace, and edit `charts/amq-operator-on-openshift.yaml` to replace `openshift-operators` with your project namespace. Then apply both files: `oc apply -f ./charts/amq-operator-group-on-openshift.yaml && oc apply -f ./charts/amq-operator-on-openshift.yaml`

To verify the operator is ready to use, you can run the following command. You should see the following output.
The `PHASE` needs to be `Succeeded`
[options="nowrap",subs="+attributes"]
----
$ oc get ClusterServiceVersion -n openshift-operators
NAME                   DISPLAY                    VERSION    REPLACES               PHASE
amqstreams.v3.0.1-3    Streams for Apache Kafka   3.0.1-3    amqstreams.v3.0.1-2    Succeeded
----

NOTE: For namespace-scoped installation: To verify the operator is ready to use remove the `-n openshift-operators` parameter.

Then you can set up a Kafka cluster called `my-cluster` in your project:
[options="nowrap",subs="+attributes"]
----
$ oc apply -f ./charts/kafka-on-openshift.yaml --wait --timeout=10m0s
----

Once the Kafka cluster is ready, create the topic `testing`:
[options="nowrap",subs="+attributes"]
----
$ oc apply -f ./charts/kafka-topic.yaml --wait --timeout=10m0s
----

Although the above commands will return pretty immediately, your AMQ Streams instance will not be available until its entity operator is up and running. The name of the pod will be of the format `my-cluster-entity-operator-xxxxxxxxx-yyyyy`.

To be on the safe side, wait until this pod is ready, as shown in this example:
[options="nowrap",subs="+attributes"]
----
$   oc get pods -w
NAME                      READY   STATUS              RESTARTS   AGE
my-cluster-broker-0       0/1     ContainerCreating   0          10s
....
my-cluster-broker-0       1/1     Running             0          71s
my-cluster-broker-1       1/1     Running             0          71s
my-cluster-broker-2       1/1     Running             0          72s
my-cluster-entity-operator-7985c76b85-h6jc4   0/1     Pending             0          0s
...
my-cluster-entity-operator-7985c76b85-h6jc4   1/1     Running             0          20s
----