name: WildFly Quickstarts Kubernetes CI
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    # kubernetes-testing is a temporary entry
    branches: [main, kubernetes-testing]
# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  test-on-kubernetes:
    name: Build and test on Kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Output event
        run: echo "${{ toJSON(github.event) }}"