name: WildFly microprofile-reactive-messaging-kafka Quickstart CI

on:
  # TEMP
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'microprofile-reactive-messaging-kafka/**'
      - '.github/workflows/quickstart_ci.yml'
jobs:
  call-quickstart_ci:
    uses: ./.github/workflows/quickstart_ci.yml
    with:
      QUICKSTART_PATH: microprofile-reactive-messaging-kafka
      MICROPROFILE: true