name: WildFly helloworld Quickstart CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'helloworld/**'
      - '.github/workflows/quickstart_ci.yml'
      - '.github/workflows/quickstart_helloworld_ci.yml'

env:
  QUICKSTART_PATH: helloworld
  TEST_PROVISIONED_SERVER: true
  TEST_BOOTABLE_JAR: false
  TEST_OPENSHIFT: true
  MATRIX_OS: '"ubuntu-latest", "windows-latest"'

# Only run the latest job
concurrency:
  group: '${{ github.workflow }} @ ${{ github.ref || github.run_id }}'
  cancel-in-progress: true

jobs:
  Test-build-default-matrix:
    name: BUILD DEFAULT - JDK${{ matrix.jdk }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        jdk: [11, 17]
        os: ${{ fromJSON(toJSON('os=[${{ env.MATRIX_OS }}]')) }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: quickstarts
      - name: Run before script
        env:
           FILE: "./quickstarts/.github/workflows/quickstart_${{ env.QUICKSTART_PATH }}_ci_before.sh"
        run: |          
          if test -f $FILE;
            then
              chmod +x $FILE 
              bash $FILE
          fi
        shell: bash
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'temurin'
          cache: 'maven'
      - name: Run after script
        env:
          FILE: "./quickstarts/.github/workflows/quickstart_${{ env.QUICKSTART_PATH }}_ci_after.sh"
        run: |
          if test -f $FILE;
            then
              chmod +x $FILE 
              bash $FILE
          fi
        shell: bash